#!/usr/bin/env bash
# Copyright (c) 2024 The Toltec Contributors
# SPDX-License-Identifier: MIT

archs=(rm1 rm2 rmpp rmppm)
pkgnames=(lf)
pkgdesc="Terminal file manager"
url=https://github.com/gokcehan/lf
pkgver=r32-2
timestamp=2024-03-31T20:04Z
section="utils"
maintainer="gbyl <gbyl@users.noreply.github.com>"
license=MIT
installdepends=(libncurses-dev)

image=golang:v3.2
image_rmpp=golang:v4.0
image_rmppm=golang:v4.0

source=("https://github.com/gokcehan/lf/archive/refs/tags/${pkgver%-*}.zip")
sha256sums=(571ee17d8181d77a3b8bcd7aaaff0bde062c1851d93e9d324dfe15948136891a)

build() {
    case $arch in
        rm1 | rm2)
            export GOARCH=arm
            ;;
        rmpp | rmppm)
            export GOARCH=arm64
            ;;
        *)
            echo "Unhandled arch: $arch"
            exit 1
            ;;
    esac
    go build
}

package() {
    install -D -m 755 "$srcdir"/lf "$pkgdir"/opt/bin/lf
}
