#!/usr/bin/env bash
# Copyright (c) 2023 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(lf)
pkgdesc="Terminal file manager"
url=https://github.com/gokcehan/lf
pkgver=r31-1
timestamp=2023-09-17T12:55Z
section="utils"
maintainer="gbyl <gbyl@users.noreply.github.com>"
license=MIT

image=golang:v3.1
source=("https://github.com/gokcehan/lf/archive/refs/tags/${pkgver%-*}.zip")
sha256sums=(217e152f09ae0cc8ab8f12fd92f705dd12630907de2b6a78ffc2727950921f97)

build() {
    export GOARCH=arm
    go build
}

package() {
    install -D -m 755 "$srcdir"/lf "$pkgdir"/opt/bin/lf
}
