#!/usr/bin/env bash
# Copyright (c) 2021 The Toltec Contributors
# SPDX-License-Identifier: MIT

archs=(rm2)
pkgnames=(linux-mainline)
pkgdesc="reMarkable 2 kernel based on the mainline kernel"
url=https://www.kernel.org
pkgver=5.19.0-1
timestamp=2022-05-22T21:50:09Z
section=kernel
maintainer="Alistair Francis <alistair@alistair23.me>"
makedepends=(build:flex build:bison build:libssl-dev build:bc build:lzop build:libgmp-dev build:libmpc-dev)
license=GPL-2.0-only
flags=(nostrip)

image=base:v2.3
source=("https://github.com/alistair23/linux/archive/6df274810d20448125834115e2181de288fdc8a4.tar.gz")
sha256sums=(a7538198dbef21868d2c52e8b379576c8791726809bd5886176ab88d1f9df49f)

build() {
    ARCH=arm make imx_v6_v7_defconfig
    ARCH=arm make -j8
}

package() {
    # Prepare files for the kernel archive
    local staging="$srcdir"/staging
    mkdir -p "$staging/boot"

    cp --no-dereference {"$srcdir"/arch/arm,"$staging"}/boot/zImage
    cp --no-dereference "$srcdir"/arch/arm/boot/dts/imx7d-remarkable2.dtb \
        "$staging"/boot/zero-sugar.dtb

    ARCH=arm make -C "$srcdir" modules_install INSTALL_MOD_PATH="$staging"
    rm "$staging"/lib/modules/*/{source,build}

    # Create the kernel archive
    local archive="mainline-${pkgver%-*}.tar.bz2"
    install -d "$pkgdir"/opt/usr/share/kernelctl
    (cd "$staging" && tar --owner root:0 --group root:0 --mtime=$timestamp \
        -cjf "$pkgdir"/opt/usr/share/kernelctl/"$archive" boot/* lib/modules/*)
}

configure() {
    echo "The new kernel files have been copied, but not installed."
    echo "Please use kernelctl to select the kernel to boot."
    echo
    echo "Known issues with the mainline kernel:"
    echo " - No support for low power mode (suspend uses more power then it should)"
    echo " - WiFi sometimes is off on boot (can be turned on again though)"
    echo " - GUI shutdown in Oxide doesn't work"
    echo " - Wacom stylus doesn't work in Xochitl (works everywhere else though)"
    echo " - No OTG control support"
}

postremove() {
    echo "To restore to the original kernel, run and then reboot"
    echo "  rm -rf /lib/modules/${pkgver%-*}/"
    echo "  cp -f /home/root/boot-backup/zImage /boot/"
    echo "  cp -f /home/root/boot-backup/zero-sugar.dtb /boot/"
    echo "  /bin/sync"
}
