#!/usr/bin/env bash
# Copyright (c) 2021 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(netevent)
pkgdesc="Input-Event device cloning utility"
url="https://github.com/Blub/netevent"
pkgver=2.2.2-1
timestamp=2023-04-29T14:21:02Z
section=utils
maintainer="Salvatore Stella <etn45p4m@gmail.com>"
license=GPL-2.0-only

image=base:v2.2
source=(
    "https://github.com/Blub/netevent/archive/refs/tags/${pkgver%-*}.tar.gz"
)
sha256sums=(
    09c0e97cd5c2cf5ed51e44ce955cc28cfa2cd0022bd48241f1096bc441439d3a
)

build() {
    export CXX="${CROSS_COMPILE}g++"
    make
}

package() {
    install -D -m 755 "$srcdir"/netevent "$pkgdir"/opt/bin/netevent
}
