#!/usr/bin/env bash
# Copyright (c) 2020 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(netevent)
pkgdesc="Input-Event device cloning utility"
url="https://github.com/Blub/netevent"
pkgver=2.2.1-1
timestamp=2021-12-03T19:43:04+01:00
section=utils
maintainer="Salvatore Stella <etn45p4m@gmail.com>"
license=GPL-2.0-only

image=base:v2.2
source=(
    https://github.com/Blub/netevent/archive/refs/tags/2.2.1.tar.gz
)
sha256sums=(
    ba1289cc04aef563baa9cc203111af3980a9311442233ffcf76760cda9f6aa69
)

build() {
    export CXX=arm-linux-gnueabihf-g++
    make
}

package() {
    install -D -m 755 "$srcdir"/netevent "$pkgdir"/opt/bin/netevent
}
