#!/usr/bin/env bash
# Copyright (c) 2020 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(rmservewacominput)
pkgdesc="Serve pen input on port 33333"
url=https://github.com/LinusCDE/rmWacomToMouse
pkgver=0.3.0-1
timestamp=2021-03-10T18:36Z
section="utils"
maintainer="Linus K. <linus@cosmos-ink.net>"
license=MIT
depends=(appmarkable)

image=base:v1.4
source=(
    https://github.com/LinusCDE/rmWacomToMouse/archive/1a45d3446c8bc11de04800a702576056016875ed.zip
    rmservewacominput.draft
    rmservewacominput_gui
)
sha256sums=(
    4d51ff9d6b8f57fe4970b4a0adebafe3513ddeb521a2707b81a42d32f73dadb1
    SKIP
    SKIP
)

build() {
    cd c_implementation
    CC=arm-linux-gnueabihf-gcc make
}

package() {
    install -D -m 755 "$srcdir"/c_implementation/rmServeWacomInput "$pkgdir"/opt/bin/rmservewacominput
    install -D -m 755 "$srcdir"/rmservewacominput_gui "$pkgdir"/opt/bin/rmservewacominput_gui
    install -D -m 644 "$srcdir"/rmservewacominput.draft "$pkgdir"/opt/etc/draft/rmservewacominput.draft
    install -D -m 644 "$srcdir"/icon.png "$pkgdir"/opt/etc/draft/icons/rmservewacominput.png
}
