#!/bin/bash

# Copyright (c) 2021 The Toltec Contributors
# SPDX-License-Identifier: MIT

exec /opt/bin/appmarkable /opt/bin/rmservewacominput -n rmServeWacomInput -i /opt/etc/draft/icons/rmservewacominput.png
