#!/usr/bin/env bash
# Copyright (c) 2021 The Toltec Contributors
# SPDX-License-Identifier: MIT

archs=(rm1 rm2)
pkgnames=(netsurf)
pkgdesc="Lightweight web browser"
url=https://github.com/alex0809/netsurf-reMarkable
pkgver=0.4.0-5
timestamp=2024-09-04T21:14+00:00
maintainer="Alex Friesenhahn <rm-dev@alexfriesenhahn.de>"
license=GPL-2.0-or-later
section="readers"
makedepends=(
    build:automake
    build:bison
    build:flex
    build:git
    build:gperf
    build:libpng-dev
    build:libtool
)
installdepends=(
    display
    dejavu-fonts-ttf-DejaVuSans
    dejavu-fonts-ttf-DejaVuSans-Bold
    dejavu-fonts-ttf-DejaVuSans-BoldOblique
    dejavu-fonts-ttf-DejaVuSans-Oblique
    dejavu-fonts-ttf-DejaVuSerif
    dejavu-fonts-ttf-DejaVuSerif-Bold
    dejavu-fonts-ttf-DejaVuSerif-Italic
    dejavu-fonts-ttf-DejaVuSansMono
    dejavu-fonts-ttf-DejaVuSansMono-Bold
)
image=base:v3.2
flags=(patch_rm2fb)

source=(
    https://github.com/alex0809/netsurf-reMarkable/archive/11ba4e18c65c687693c03d58da329e90662282e8.zip
    https://gitlab.freedesktop.org/freetype/freetype/-/archive/VER-2-10-4/freetype-VER-2-10-4.tar.gz
    netsurf.draft
)
sha256sums=(
    18813be8d3492bdfc6d498ee62e32c691a329b64388970c04ca4ce8b3e656241
    4d47fca95debf8eebde5d27e93181f05b4758701ab5ce3e7b3c54b937e8f0962
    SKIP
)
noextract=(
    libiconv-1.16.tar.gz
    freetype-VER-2-10-4.tar.gz
    2.0.90
)

prepare() {
    set -e
    (
        # toltecmk times out when trying to download this, but manual curl works fine
        if [ -f libiconv-1.16.tar.gz ] && ! echo "e6a1b1b589654277ee790cce3734f07876ac4ccfaecbee8afa0b649cf529cc04  libiconv-1.16.tar.gz" | sha256sum -c; then
            rm libiconv-1.16.tar.gz
        fi
        if ! [ -f libiconv-1.16.tar.gz ]; then
            curl https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.16.tar.gz -o libiconv-1.16.tar.gz
        fi
        echo "e6a1b1b589654277ee790cce3734f07876ac4ccfaecbee8afa0b649cf529cc04  libiconv-1.16.tar.gz" | sha256sum -c
        mkdir -p libiconv
        cd libiconv
        tar --strip-components=1 -xf ../libiconv-1.16.tar.gz
    ) &

    (
        if [ -f libjpeg-turbo.tar.gz ] && ! echo "6a965adb02ad898b2ae48214244618fe342baea79db97157fdc70d8844ac6f09  libjpeg-turbo.tar.gz" | sha256sum -c; then
            rm libjpeg-turbo.tar.gz
        fi
        if ! [ -f libjpeg-turbo.tar.gz ]; then
            curl https://codeload.github.com/libjpeg-turbo/libjpeg-turbo/tar.gz/refs/tags/2.0.90 -o libjpeg-turbo.tar.gz
        fi
        echo "6a965adb02ad898b2ae48214244618fe342baea79db97157fdc70d8844ac6f09  libjpeg-turbo.tar.gz" | sha256sum -c
        mkdir -p libjpeg-turbo
        cd libjpeg-turbo
        tar --strip-components=1 -xf ../libjpeg-turbo.tar.gz
    ) &

    (
        mkdir -p freetype
        cd freetype
        tar --strip-components=1 -xf ../freetype-VER-2-10-4.tar.gz
    ) &
    wait $(jobs -p)
}

build() {
    set -e
    ln -s /usr/bin/which /bin
    export MAKEFLAGS="-j$(nproc)"
    export DEBIAN_FRONTEND=noninteractive

    (
        # Build libiconv 1.16
        cd libiconv
        ./configure \
            --prefix="$SYSROOT/usr" \
            --host="$CHOST" \
            --enable-static \
            --disable-shared
        make
        make install
    ) &
    (
        # Build FreeType 2.10.4
        cd freetype
        bash autogen.sh
        ./configure \
            --without-zlib \
            --without-png \
            --enable-static=yes \
            --enable-shared=no \
            --without-bzip2 \
            --host=arm-linux-gnueabihf \
            --host="$CHOST" \
            --disable-freetype-config
        make
        DESTDIR="$SYSROOT" make install
    ) &

    (
        # Build libjpeg-turbo 2.0.90
        cd libjpeg-turbo
        cmake \
            -DCMAKE_SYSROOT="$SYSROOT" \
            -DCMAKE_TOOLCHAIN_FILE="/usr/share/cmake/$CHOST.cmake" \
            -DCMAKE_INSTALL_LIBDIR="$SYSROOT/lib" \
            -DCMAKE_INSTALL_INCLUDEDIR="$SYSROOT/usr/include" \
            -DENABLE_SHARED=FALSE
        make
        make install
    ) &

    wait $(jobs -p)
    TARGET_WORKSPACE=$(pwd)/build scripts/build.sh
}

package() {
    # Netsurf binary
    install -d "$pkgdir"/opt/bin
    install -D -m 755 "$srcdir"/build/netsurf/nsfb "$pkgdir"/opt/bin/netsurf

    # Draft launcher file
    install -d "$pkgdir"/opt/etc/draft
    install -D -m 644 "$srcdir"/netsurf.draft "$pkgdir"/opt/etc/draft/

    # Resources
    install -d "$pkgdir"/opt/usr/share/netsurf
    resdir="$srcdir"/build/netsurf/frontends/framebuffer/res
    install -D -m 644 -t "$pkgdir"/opt/usr/share/netsurf/ \
        "$resdir"/adblock.css \
        "$resdir"/default.css \
        "$resdir"/quirks.css \
        "$resdir"/internal.css \
        "$resdir"/Messages \
        "$resdir"/credits.html \
        "$resdir"/licence.html \
        "$resdir"/welcome.html \
        "$resdir"/welcome-netsurf.html \
        "$resdir"/netsurf.png

    # Default Choices file
    install -D -m 644 "$srcdir"/example/Choices "$pkgdir"/opt/usr/share/netsurf/Choices
}
