#!/usr/bin/env bash
# Copyright (c) 2020 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(rm1 rm2)
pkgdesc="Ensure packages are not installed on the wrong device"
pkgver=0.1.0-2
url=https://github.com/toltec-dev/toltec
timestamp=2020-12-25T22:21Z
section=meta
maintainer="Linus K. <linus@cosmos-ink.net>"
license=MIT

rm1() {
    conflicts=(rm2)

    package() { :; }

    preinstall() {
        local supported_machine_names
        local actual_machine_name
        supported_machine_names=('reMarkable 1.0' 'reMarkable Prototype 1')
        actual_machine_name=$(cat /sys/devices/soc0/machine)

        if [[ ! "${supported_machine_names[*]}" =~ $actual_machine_name ]]; then
            echo "Your devices got identified as: $actual_machine_name" >&2
            echo "You are attempting to install the package \"rm1\" on something else." >&2
            echo "This package should not get installed here. Please uninstall it now:" >&2
            echo "$ opkg remove rm1  (add --force-remove it fails)" >&2
            exit 1
        fi
    }
}

rm2() {
    conflicts=(rm1)

    package() { :; }

    preinstall() {
        local supported_machine_names
        local actual_machine_name
        supported_machine_names=('reMarkable 2.0')
        actual_machine_name=$(cat /sys/devices/soc0/machine)

        if [[ ! "${supported_machine_names[*]}" =~ $actual_machine_name ]]; then
            echo "Your devices got identified as: $actual_machine_name" >&2
            echo "You are attempting to install the package \"rm2\" on something else." >&2
            echo "This package should not get installed here. Please uninstall it now:" >&2
            echo "$ opkg remove rm2  (add --force-remove it fails)" >&2
            exit 1
        fi
    }
}
