#!/usr/bin/env bash
# Copyright (c) 2021 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(innernet-client)
pkgdesc="A private network system that uses WireGuard under the hood."
url="https://github.com/tonarino/innernet"
pkgver=1.3.0-beta-5-1
timestamp=2021-05-19T08:17:04Z
section="utils"
maintainer="plan5 <30434574+plan5@users.noreply.github.com>"
license=MIT
installdepends=(wireguard)
makedepends=(build:librust-clang-sys-dev build:libclang-dev build:libc6 build:libc6-dev build:clang build:gcc-multilib build:g++-multilib)

image=rust:v1.4
source=(https://github.com/tonarino/innernet/archive/refs/tags/v1.3.0-beta.5.zip)
sha256sums=(2fb9b6ea36c437f79ae1825af86c41350d1ed9fa58cc844a1b120f78f707be03)

prepare() {
    # Change config folders to live under /opt
    sed -i "s/\/etc\/innernet/\/opt\/etc\/innernet/g" "$srcdir/shared/src/lib.rs"
    sed -i "s/\/var\/lib\/innernet/\/opt\/var\/lib\/innernet/g" "$srcdir/shared/src/lib.rs"

    #Change binary path in service file
    sed -i "s/\/usr\/bin\/innernet/\/opt\/bin\/innernet/g" "$srcdir/client/innernet@.service"

    #tbd: change wireguard config dir to /opt/etc/wireguard?
    #sed -i "s/\/etc\/wireguard/\/opt\/etc\/wireguard/g" "$srcdir/shared/src/lib.rs"
}

build() {
    cargo build --release --bin innernet
}

package() {
    install -D -m 700 -t "$pkgdir"/opt/bin "$srcdir"/target/armv7-unknown-linux-gnueabihf/release/innernet
    install -D -m 644 -t "$pkgdir"/lib/systemd/system "$srcdir/client/innernet@.service"
    install -D -m 644 -t "$pkgdir"/lib/systemd/system "$srcdir/client/innernet.target"

    # Link /opt/bin/innernet to /opt/bin/inn
    ln -s /opt/bin/innernet "$pkgdir"/opt/bin/inn
}

configure() {
    if ! [ -d /opt/var/lib/innernet ]; then
        mkdir -p /opt/var/lib/innernet
    fi
}
