#!/usr/bin/env bash
# Copyright (c) 2023 The Toltec Contributors
# SPDX-License-Identifier: MIT

archs=(
    rm1os2
    rm1os3
    rm1os3v22
    rm2os2
    rm2os3
    rm2os3v22
    rmppos3v22
    rmppmos3v22
)
pkgnames=(toltec-deletions)
pkgdesc="Metapackage to handle package deletions between OS versions"
url=https://toltec-dev.org/
pkgver=0.2-1
timestamp=2025-11-02T00:00Z
section="utils"
maintainer="Eeems <eeems@eeems.email>"
license=MIT
installdepends=(toltec-bootstrap)

replaces_rm1os2=()
conflicts_rm1os2=("${replaces_rm1os2[@]}")

replaces_rm2os2=()
conflicts_rm2os2=("${replaces_rm2os2[@]}")

replaces_rm1os3=(
    ddvk-hacks
    fuse
    wireguard
    innernet-client
    gocryptfs
    remarkable-stylus
)
conflicts_rm1os3=("${replaces_rm1os3[@]}")

replaces_rm1os3v22=(
    "${replaces_rm1os3[@]}"
    oxide
    oxide-extra
    oxide-utils
    inject_evdev
    liboxide
    liboxide-dev
    libsentry
    reterm
    signature-rm
)
conflicts_rm1os3v22=("${replaces_rm1os3v22[@]}")

replaces_rm2os3=(
    ddvk-hacks
    fuse
    wireguard
    innernet-client
    gocryptfs
    remarkable-stylus
    open-remarkable-shutdown
)
conflicts_rm2os3=("${replaces_rm2os3[@]}")

replaces_rm2os3v22=(
    "${replaces_rm2os3[@]}"
    oxide
    oxide-extra
    oxide-utils
    inject_evdev
    liboxide
    liboxide-dev
    libsentry
    reterm
    signature-rm
)
conflicts_rm2os3v22=("${replaces_rm2os3v22[@]}")

replaces_rmppos3v22=()
conflicts_rmppos3v22=("${replaces_rmppos3v22[@]}")

replaces_rmppmos3v22=()
conflicts_rmppmos3v22=("${replaces_rmppmos3v22[@]}")

source=()
sha256sums=()

package() {
    # This should be fully reinstalled on reenable
    # So add a file to root
    mkdir -p "$pkgdir"/usr/share/toltec/reenable.d
    touch "$pkgdir"/usr/share/toltec/reenable.d/toltec-deletions
}
