name: Setup Toltec dependencies
runs:
    using: "composite"
    steps:
        - name: Install Ubuntu packages
          shell: bash
          run: |
            sudo apt-get update -yq
            sudo apt-get install -yq libarchive-tools
        - name: Install shfmt and Shellcheck
          shell: bash
          run: |
            install_dir=/usr/local/bin

            # Install shfmt
            shfmt_version=v3.2.1
            shfmt_checksum=43439b996942b53dfafa9b6ff084f394555d049c98fb7ec37978f7668b43e1be
            sudo curl --location --silent --fail --tlsv1.2 --proto '=https' \
                --output "$install_dir"/shfmt \
                https://github.com/mvdan/sh/releases/download/"$shfmt_version"/shfmt_"$shfmt_version"_linux_amd64
            sha256sum -c <(echo "$shfmt_checksum $install_dir/shfmt") > /dev/null 2>&1
            sudo chmod a+x "$install_dir"/shfmt

            # Install Shellcheck (Ubuntu’s version is too old)
            shellcheck_version=v0.7.1
            shellcheck_checksum=64f17152d96d7ec261ad3086ed42d18232fcb65148b44571b564d688269d36c8
            shellcheck_arname=shellcheck.tar.xz
            curl --location --silent --fail --tlsv1.2 --proto '=https' \
                --output "$shellcheck_arname" \
                https://github.com/koalaman/shellcheck/releases/download/"$shellcheck_version"/shellcheck-"$shellcheck_version".linux.x86_64.tar.xz
            sha256sum -c <(echo "$shellcheck_checksum $shellcheck_arname") > /dev/null 2>&1
            tar -xf "$shellcheck_arname" --strip-components=1 \
                shellcheck-"$shellcheck_version"/shellcheck
            rm "$shellcheck_arname"
            chmod a+x shellcheck
            sudo chown root:root shellcheck
            sudo mv shellcheck "$install_dir"
        - name: Install Python dependencies
          shell: bash
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
