#!/usr/bin/env bash
# Copyright (c) 2021 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(toltec-bootstrap)
pkgdesc="Manage your Toltec install"
url=https://toltec-dev.org/
pkgver=0.0.8-1
timestamp=2021-06-22T08:38Z
section="utils"
maintainer="Eeems <eeems@eeems.email>"
license=MIT

source=(toltecctl)
sha256sums=(SKIP)

package() {
    install -D -m 744 -t "$pkgdir"/home/root/.local/bin "$srcdir"/toltecctl
}

configure() {
    /home/root/.local/bin/toltecctl set-path
}
