#!/usr/bin/env bash
# Copyright (c) 2020 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(wg-tools)
pkgdesc="WireGuard userspace control programs (wg and wg-quick)"
url=https://www.wireguard.com
pkgver=1.0.20200827-1
timestamp=2020-08-27T08:22Z
section=utils
maintainer="Jonah Weissman <jonahrweissman+toltec@gmail.com>"
license=GPL-2.0-only

image=base:v1.3.2
source=(
    "https://git.zx2c4.com/wireguard-tools/snapshot/wireguard-tools-${pkgver%-*}.tar.xz"
)
noextract=("wireguard-tools-${pkgver%-*}.tar.xz")
sha256sums=(51bc85e33a5b3cf353786ae64b0f1216d7a871447f058b6137f793eb0f53b7fd)

prepare() {
    bsdtar -x \
        --directory "$srcdir" \
        --file "$srcdir/"wireguard-tools-1.0.20200827.tar.xz
    mv "$srcdir/"wireguard-tools-1.0.20200827/* "$srcdir"
    # the symlink at src/wg-quick/wg needs something to point to
    touch "$srcdir/src/wg"
}

build() {
    make -C src PLATFORM=linux "CC=${CROSS_COMPILE}cc"
}

package() {
    make -C "$srcdir/src" DESTDIR="$pkgdir/" WITH_WGQUICK=yes \
        WITH_SYSTEMDUNITS=yes WITH_BASHCOMPLETION=no install
}
