#!/usr/bin/env bash
# Copyright (c) 2020 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(fingerterm)
pkgdesc="Terminal emulator with an on-screen touch keyboard"
url=https://github.com/dixonary/fingerterm-reMarkable
pkgver=1.3.5-12
timestamp=2021-01-18T6:38Z
section="admin"
maintainer="Mattéo Delabre <spam@delab.re>"
license=GPL-2.0-or-later

image=qt:v1.1
source=(
    https://github.com/dixonary/fingerterm-reMarkable/archive/f192efa794e48dad36354c066f7dfee4c0338dd8.zip
    fingerterm.png
    fingerterm.draft
)
sha256sums=(
    8a105b89cc938db12598aa0d7b064ce059a35385050eaaf26828915dfa1189a4
    SKIP
    SKIP
)

build() {
    sed -i 's,DEPLOYMENT_PATH = /usr,DEPLOYMENT_PATH = /opt,' fingerterm.pro
    qmake fingerterm.pro
    make
}

package() {
    install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/fingerterm

    install -d "$pkgdir"/opt/share/fingerterm
    install -D -m 644 -t "$pkgdir"/opt/share/fingerterm "$srcdir"/qml/*
    cp -r "$srcdir"/icons "$pkgdir"/opt/share/fingerterm
    cp -r "$srcdir"/data "$pkgdir"/opt/share/fingerterm

    install -D -m 644 -t "$pkgdir"/opt/etc/draft "$srcdir"/fingerterm.draft
    install -D -m 644 -t "$pkgdir"/opt/etc/draft/icons "$srcdir"/fingerterm.png
}
