#!/usr/bin/env bash
# Copyright (c) 2020 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(micro)
pkgdesc="Modern and intuitive terminal-based text editor"
url=https://micro-editor.github.io/
pkgver=2.0.10-1
timestamp=2021-08-07T00:57:40Z
section="utils"
maintainer="Eeems <eeems@eeems.email>"
license=MIT

source=(https://github.com/zyedidia/micro/releases/download/v2.0.10/micro-2.0.10-linux-arm.tar.gz)
sha256sums=(b60478ac87f41f00d91cf6ca58b6d7e05af99ee5fa73fa8881b140ac428fa278)

package() {
    install -Dm644 "$srcdir"/LICENSE "$pkgdir/opt/usr/share/licenses/$pkgname/LICENSE"
    install -Dm644 "$srcdir"/LICENSE-THIRD-PARTY "$pkgdir/opt/usr/share/licenses/$pkgname/LICENSE-THIRD-PARTY"
    install -Dm644 "$srcdir"/micro.1 "$pkgdir/opt/share/man/man1/micro.1"
    install -Dm744 "$srcdir"/micro "$pkgdir/opt/bin/micro"
}
