#!/usr/bin/env bash
# Copyright (c) 2020 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(micro)
pkgdesc="Modern and intuitive terminal-based text editor"
url=https://micro-editor.github.io/
pkgver=2.0.9-1
timestamp=2021-05-16T20:49:48Z
section="utils"
maintainer="Eeems <eeems@eeems.email>"
license=MIT

source=(https://github.com/zyedidia/micro/releases/download/v2.0.9/micro-2.0.9-linux-arm.tar.gz)
sha256sums=(3041fc74beac491c96e8685dd23e034df0341095a0e46512e32b232c0e2d0e1f)

package() {
    install -Dm644 "$srcdir"/LICENSE "$pkgdir/opt/usr/share/licenses/$pkgname/LICENSE"
    install -Dm644 "$srcdir"/LICENSE-THIRD-PARTY "$pkgdir/opt/usr/share/licenses/$pkgname/LICENSE-THIRD-PARTY"
    install -Dm644 "$srcdir"/micro.1 "$pkgdir/opt/share/man/man1/micro.1"
    install -Dm744 "$srcdir"/micro "$pkgdir/opt/bin/micro"
}
