#!/usr/bin/env bash
# Copyright (c) 2020 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(remarkable_math_graph)
pkgdesc="An example template for the reMarkable tablet"
url=https://github.com/PeterGrace/remarkable_math_graph
pkgver=0.0.2-1
timestamp=2021-01-14T02:03Z
section=utils
maintainer="Peter Grace <pete.grace@gmail.com>"
license=MIT
depends=(templatectl)

image=qt:v1.2.2
source=(https://github.com/PeterGrace/remarkable_math_graph/archive/v0.0.2.zip)
sha256sums=(f782efc048af932bd34a2390f757aecb9b5b422980ed516b99431ac0f8891926)

build() {
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -y
    apt-get install -y \
        --no-install-recommends \
        -o Dpkg::Options::="--force-confdef" \
        imagemagick librsvg2-bin
	convert -scale 26.464% remarkable_math_graph_qcadexport.svg \
        remarkable_math_graph.svg
    convert remarkable_math_graph.svg remarkable_math_graph.png
}

package() {
    install -D -m 755 -t "$pkgdir"/usr/share/remarkable/templates \
        "$srcdir"/remarkable_math_graph.png
    install -D -m 755 -t "$pkgdir"/usr/share/remarkable/templates \
        "$srcdir"/remarkable_math_graph.svg
}

configure() {
    templatectl add -n "Math Graph" -f "remarkable_math_graph" -c "Custom" \
        -c "Math"
}

preremove() {
    templatectl remove -n "Math Graph"
}
