#!/usr/bin/env bash
pkgname=chessmarkable
pkgdesc="A chess game for the reMarkable"
url=https://github.com/LinusCDE/chessmarkable
pkgver=0.4.1-1
timestamp=2020-10-09T16:44Z
section=games
maintainer="Linus K. <linus@cosmos-ink.net>"
license=MIT

image=rust:v1.1
source=(https://github.com/LinusCDE/chessmarkable/archive/3cdf768e455d6d9cb48b05cdcd4513c195a36f00.zip)
sha256sums=(b0a6f2ac646555305c9863e268341d6f36c4f8e6b77dc7abffe374c1fadc464d)

build() {
    # Fall back to system-wide config
    rm .cargo/config

    cargo build --release
    arm-linux-gnueabihf-strip target/armv7-unknown-linux-gnueabihf/release/chessmarkable
}

package() {
    install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/target/armv7-unknown-linux-gnueabihf/release/chessmarkable
    install -D -m 644 "$srcdir"/oxide "$pkgdir"/opt/etc/draft/chessmarkable
    install -D -m 644 "$srcdir"/icon.png "$pkgdir"/opt/etc/draft/icons/chessmarkable.png
}
