#!/usr/bin/env bash
# Copyright (c) 2021 The Toltec Contributors
# SPDX-License-Identifier: MIT

archs=(rm1 rm2 rmpp rmppm)
pkgnames=(rmfakecloud-proxy)
pkgdesc="Connect Xochitl to a rmfakecloud server"
_url=https://github.com/ddvk/rmfakecloud-proxy
url="$_url"
_upver=0.0.8
pkgver="$_upver-1"
timestamp=2025-08-20T15:50:55Z
section="utils"
maintainer="Mattéo Delabre <spam@delab.re>"
license=MIT
installdepends=(procps-ng-pgrep findutils)

image=golang:v3.2
image_rmpp=golang:v4.0
image_rmppm=golang:v4.0
source=(
    "https://github.com/ddvk/rmfakecloud-proxy/archive/v$_upver.zip"
    rmfakecloudctl
    rmfakecloud-proxy.service
)
sha256sums=(
    81778d159a5d2d5e2f6d585c159e21f84ccc3b8dacdd5cda785aa47aa9b7658d
    SKIP
    SKIP
)

build() {
    eval "$(go env)"
    cat > version.go << GO
package main
const Version = "rmfakecloud-proxy ${_upver%-*} ($GOOS-$GOARCH) $GOVERSION\n$_url"
GO
    case $arch in
        rm1 | rm2)
            GOARCH=arm GOARM=7 go build -ldflags="-w -s" -o dist/rmfakecloud-proxy
            ;;
        rmpp | rmppm)
            GOARCH=arm64 go build -ldflags="-w -s" -o dist/rmfakecloud-proxy
            ;;
        *)
            echo "Unhandled arch: $arch"
            exit 1
            ;;
    esac
}

package() {
    install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/dist/rmfakecloud-proxy
    install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/rmfakecloudctl
    install -D -m 644 -t "$pkgdir"/lib/systemd/system "$srcdir"/rmfakecloud-proxy.service
}

configure() {
    # shellcheck source=rmfakecloudctl
    source /opt/bin/rmfakecloudctl
    systemctl daemon-reload

    # Sync the proxy state to the value of its configuration flag
    if is-enabled; then
        # This branch is reached when upgrading the package
        install-certificates
        systemctl enable --now rmfakecloud-proxy
        install-hosts
    else
        uninstall-certificates
        disable-unit rmfakecloud-proxy.service
        uninstall-hosts
    fi

    rmfakecloudctl status
}

preremove() {
    rmfakecloudctl disable
}

postremove() {
    systemctl daemon-reload
}
