#!/usr/bin/env bash
# Copyright (c) 2021 The Toltec Contributors
# SPDX-License-Identifier: MIT
ln -sf rm2fb.01 /dev/shm/swtfb.01
LD_PRELOAD=/opt/lib/librm2fb_server.so exec -a "rm2fb-server" /usr/bin/xochitl
