#!/usr/bin/env bash
# Copyright (c) 2020 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(
    dotnet-profile
    dotnet-host
    dotnet-sdk
    dotnet-runtime
    aspnet-runtime
    dotnet-targeting-pack
    aspnet-targeting-pack
    netstandard-targeting-pack
)
pkgver=3.1.17-1
timestamp=2021-07-13T17:38:00Z
maintainer="Eeems <eeems@eeems.email>"
url=https://www.microsoft.com/net/core
section="devel"
license=MIT

source=(
    https://github.com/dotnet/sdk/archive/refs/tags/v3.1.411.zip
    dotnet-profile.sh
)
sha256sums=(
    16befb43bcf2ac3ad005f3c6995a1204586a5bc248b7b70fe013c9030ea0b026
    SKIP
)

image=base:v2.1
build() {
    ./build.sh
    ./build.sh --test
}

dotnet-profile() {
    pkgdesc="Default profile script to ensure that the .NET Core Command Line Interface runs properly"

    package() {
        install -Dm 744 -t "$pkgdir"/etc/profile.d/ "$srcdir"/artifacts/bin/redist/Debug/dotnet/dotnet-profile.sh
    }
    configure() {
        echo "Make sure to source /etc/profile.d/dotnet-profile.sh before running dotnet"
    }
}

dotnet-host() {
    pkgdesc="Generic driver for the .NET Core Command Line Interface"
    installdepends=(dotnet-profile)

    package() {
        install -dm 755 "$pkgdir"/opt/{bin,usr/{lib,share/{dotnet,licenses/dotnet-host}}}
        cp -dr --no-preserve='ownership' "$srcdir"/artifacts/bin/redist/Debug/dotnet/{dotnet,host} "$pkgdir"/opt/usr/share/dotnet/
        cp -dr --no-preserve='ownership' "$srcdir"/artifacts/bin/redist/Debug/dotnet/{LICENSE,ThirdPartyNotices}.txt "$pkgdir"/opt/usr/share/licenses/dotnet-host
        ln -sf /opt/usr/share/dotnet/dotnet "$pkgdir"/opt/bin/dotnet
        ln -sf /opt/usr/share/dotnet/host/fxr/3.1.10/libhostfxr.so "$pkgdir"/opt/usr/lib/libhostfxr.so
    }
}
dotnet-sdk() {
    pkgdesc=".NET Core SDK"
    installdepends=(
        dotnet-runtime
        dotnet-targeting-pack
        netstandard-targeting-pack
    )

    package() {
        install -dm 755 "$pkgdir"/opt/usr/share/{dotnet,licenses}
        cp -dr --no-preserve='ownership' "$srcdir"/artifacts/bin/redist/Debug/dotnet/{sdk,templates} "$pkgdir"/opt/usr/share/dotnet/
        ln -s dotnet-host-bin "$pkgdir"/opt/usr/share/licenses/dotnet-sdk-bin
    }
}
dotnet-runtime() {
    pkgdesc=".NET Core runtime"
    installdepends=(dotnet-host icu zlib libcurl)

    package() {
        install -dm 755 "$pkgdir"/opt/usr/share/{dotnet/shared,licenses}
        cp -dr --no-preserve='ownership' "$srcdir"/artifacts/bin/redist/Debug/dotnet/shared/Microsoft.NETCore.App "$pkgdir"/opt/usr/share/dotnet/shared/
        ln -s dotnet-host-bin "$pkgdir"/opt/usr/share/licenses/dotnet-runtime-bin
    }
}
aspnet-runtime() {
    pkgdesc="ASP.NET Core runtime"
    installdepends=(dotnet-runtime)

    package() {
        install -dm 755 "$pkgdir"/opt/usr/share/{dotnet/shared,licenses}
        cp -dr --no-preserve='ownership' "$srcdir"/artifacts/bin/redist/Debug/dotnet/shared/Microsoft.AspNetCore.App "$pkgdir"/opt/usr/share/dotnet/shared/
        ln -s dotnet-host-bin "$pkgdir"/opt/usr/share/licenses/aspnet-runtime-bin
    }
}
dotnet-targeting-pack() {
    pkgdesc=".NET Core targeting pack"
    installdepends=(netstandard-targeting-pack)

    package() {
        install -dm 755 "$pkgdir"/opt/usr/share/{dotnet,dotnet/packs,licenses}
        cp -dr --no-preserve='ownership' "$srcdir"/artifacts/bin/redist/Debug/dotnet/packs/Microsoft.NETCore.App.{Host.linux-arm,Ref} "$pkgdir"/opt/usr/share/dotnet/packs/
        ln -s dotnet-host-bin "$pkgdir"/opt/usr/share/licenses/dotnet-targeting-pack-bin
    }
}
aspnet-targeting-pack() {
    pkgdesc="ASP.NET Core targeting pack"
    license=Apache
    installdepends=(dotnet-targeting-pack)

    package() {
        install -dm 755 "$pkgdir"/opt/usr/share/{dotnet,dotnet/packs,licenses}
        cp -dr --no-preserve='ownership' "$srcdir"/artifacts/bin/redist/Debug/dotnet/packs/Microsoft.AspNetCore.App.Ref "$pkgdir"/opt/usr/share/dotnet/packs/
        ln -s dotnet-host-bin "$pkgdir"/opt/usr/share/licenses/aspnet-targeting-pack-bin
    }
}
netstandard-targeting-pack() {
    pkgdesc=".NET Standard targeting pack"
    license=Apache

    package() {
        install -dm 755 "$pkgdir"/opt/usr/share/{dotnet,dotnet/packs,licenses}
        cp -dr --no-preserve='ownership' "$srcdir"/artifacts/bin/redist/Debug/dotnet/packs/NETStandard.Library.Ref "$pkgdir"/opt/usr/share/dotnet/packs/
        ln -s dotnet-host-bin "$pkgdir"/opt/usr/share/licenses/netstandard-targeting-pack
    }
}
