#!/usr/bin/env bash
# Copyright (c) 2020 The Toltec Contributors
# SPDX-License-Identifier: MIT

archs=(rm1 rm2 rmpp rmppm)
pkgnames=(
    dotnet-profile
    dotnet-host
    dotnet-sdk
    dotnet-runtime
    aspnet-runtime
    dotnet-targeting-pack
    aspnet-targeting-pack
    netstandard-targeting-pack
)
pkgver=3.1.32-1
timestamp=2022-12-13T00:00Z
maintainer="Eeems <eeems@eeems.email>"
url=https://www.microsoft.com/net/core
section="devel"
license=MIT

source_rm1=(
    https://builds.dotnet.microsoft.com/dotnet/Sdk/3.1.426/dotnet-sdk-3.1.426-linux-arm.tar.gz
    dotnet-profile.sh
)
sha256sums_rm1=(
    ec2305f43fe64a258a32cce29e77a40ddc503c95df01c9e8673af9ee5a23674e
    SKIP
)
source_rm2=(
    https://builds.dotnet.microsoft.com/dotnet/Sdk/3.1.426/dotnet-sdk-3.1.426-linux-arm.tar.gz
    dotnet-profile.sh
)
sha256sums_rm2=(
    ec2305f43fe64a258a32cce29e77a40ddc503c95df01c9e8673af9ee5a23674e
    SKIP
)
source_rmpp=(
    https://builds.dotnet.microsoft.com/dotnet/Sdk/3.1.426/dotnet-sdk-3.1.426-linux-arm64.tar.gz
    dotnet-profile.sh
)
sha256sums_rmpp=(
    7e396017a3e32b0209406c73ead9f4c03d3f521768fcd548d02a0ff5c3d45593
    SKIP
)
source_rmppm=(
    https://builds.dotnet.microsoft.com/dotnet/Sdk/3.1.426/dotnet-sdk-3.1.426-linux-arm64.tar.gz
    dotnet-profile.sh
)
sha256sums_rmppm=(
    7e396017a3e32b0209406c73ead9f4c03d3f521768fcd548d02a0ff5c3d45593
    SKIP
)

dotnet-profile() {
    pkgdesc="Default profile script to ensure that the .NET Core Command Line Interface runs properly"

    package() {
        install -Dm 744 -t "$pkgdir"/etc/profile.d/ "$srcdir"/dotnet-profile.sh
    }
    configure() {
        echo "Make sure to source /etc/profile.d/dotnet-profile.sh before running dotnet"
    }
}

dotnet-host() {
    pkgdesc="Generic driver for the .NET Core Command Line Interface"
    installdepends=(dotnet-profile)

    package() {
        install -dm 755 "$pkgdir"/opt/{bin,usr/{lib,share/{dotnet,licenses/dotnet-host}}}
        cp -dr --no-preserve='ownership' "$srcdir"/{dotnet,host} "$pkgdir"/opt/usr/share/dotnet/
        cp -dr --no-preserve='ownership' "$srcdir"/{LICENSE,ThirdPartyNotices}.txt "$pkgdir"/opt/usr/share/licenses/dotnet-host
        ln -sf /opt/usr/share/dotnet/dotnet "$pkgdir"/opt/bin/dotnet
        ln -sf /opt/usr/share/dotnet/host/fxr/3.1.10/libhostfxr.so "$pkgdir"/opt/usr/lib/libhostfxr.so
    }
}
dotnet-sdk() {
    pkgdesc=".NET Core SDK"
    installdepends=(
        dotnet-runtime
        dotnet-targeting-pack
        netstandard-targeting-pack
    )

    package() {
        install -dm 755 "$pkgdir"/opt/usr/share/{dotnet,licenses}
        cp -dr --no-preserve='ownership' "$srcdir"/{sdk,templates} "$pkgdir"/opt/usr/share/dotnet/
        ln -s dotnet-host-bin "$pkgdir"/opt/usr/share/licenses/dotnet-sdk-bin
    }
}
dotnet-runtime() {
    pkgdesc=".NET Core runtime"
    installdepends=(dotnet-host icu zlib libcurl)

    package() {
        install -dm 755 "$pkgdir"/opt/usr/share/{dotnet/shared,licenses}
        cp -dr --no-preserve='ownership' "$srcdir"/shared/Microsoft.NETCore.App "$pkgdir"/opt/usr/share/dotnet/shared/
        ln -s dotnet-host-bin "$pkgdir"/opt/usr/share/licenses/dotnet-runtime-bin
    }
}
aspnet-runtime() {
    pkgdesc="ASP.NET Core runtime"
    installdepends=(dotnet-runtime)

    package() {
        install -dm 755 "$pkgdir"/opt/usr/share/{dotnet/shared,licenses}
        cp -dr --no-preserve='ownership' "$srcdir"/shared/Microsoft.AspNetCore.App "$pkgdir"/opt/usr/share/dotnet/shared/
        ln -s dotnet-host-bin "$pkgdir"/opt/usr/share/licenses/aspnet-runtime-bin
    }
}
dotnet-targeting-pack() {
    pkgdesc=".NET Core targeting pack"
    installdepends=(netstandard-targeting-pack)

    package() {
        install -dm 755 "$pkgdir"/opt/usr/share/{dotnet,dotnet/packs,licenses}
        case $arch in
            rm1 | rm2)
                cp -dr --no-preserve='ownership' "$srcdir"/packs/Microsoft.NETCore.App.{Host.linux-arm,Ref} "$pkgdir"/opt/usr/share/dotnet/packs/
                ;;
            rmpp | rmppm)
                cp -dr --no-preserve='ownership' "$srcdir"/packs/Microsoft.NETCore.App.{Host.linux-arm64,Ref} "$pkgdir"/opt/usr/share/dotnet/packs/
                ;;
            *)
                echo "Unhandled architecture: $arc"
                exit 1
                ;;
        esac
        ln -s dotnet-host-bin "$pkgdir"/opt/usr/share/licenses/dotnet-targeting-pack-bin
    }
}
aspnet-targeting-pack() {
    pkgdesc="ASP.NET Core targeting pack"
    license=Apache
    installdepends=(dotnet-targeting-pack)

    package() {
        install -dm 755 "$pkgdir"/opt/usr/share/{dotnet,dotnet/packs,licenses}
        cp -dr --no-preserve='ownership' "$srcdir"/packs/Microsoft.AspNetCore.App.Ref "$pkgdir"/opt/usr/share/dotnet/packs/
        ln -s dotnet-host-bin "$pkgdir"/opt/usr/share/licenses/aspnet-targeting-pack-bin
    }
}
netstandard-targeting-pack() {
    pkgdesc=".NET Standard targeting pack"
    license=Apache

    package() {
        install -dm 755 "$pkgdir"/opt/usr/share/{dotnet,dotnet/packs,licenses}
        cp -dr --no-preserve='ownership' "$srcdir"/packs/NETStandard.Library.Ref "$pkgdir"/opt/usr/share/dotnet/packs/
        ln -s dotnet-host-bin "$pkgdir"/opt/usr/share/licenses/netstandard-targeting-pack
    }
}
