#!/usr/bin/env bash
# Copyright (c) 2021 The Toltec Contributors
# SPDX-License-Identifier: MIT

# Inspired by https://github.com/archlinux/svntogit-packages/blob/packages/tzdata/trunk/PKGBUILD

pkgnames=(zoneinfo-utils)
pkgdesc="Utilities for interacting with zoneinfo files"
url=https://www.iana.org/time-zones
_tzver=2021a
pkgver="$_tzver"-2
timestamp=2020-05-04T06:16Z
section=utils
maintainer="Eeems <eeems@eeems.email>"
license="custom: public domain"
installdepends=(zoneinfo-core)
makedepends=(build:gawk)

image=base:v2.3
source=(
    "https://www.iana.org/time-zones/repository/releases/tzcode${_tzver}.tar.gz"
    "https://www.iana.org/time-zones/repository/releases/tzdata${_tzver}.tar.gz"
)
sha256sums=(
    eb46bfa124b5b6bd13d61a609bfde8351bd192894708d33aa06e5c1e255802d0
    39e7d2ba08c68cbaefc8de3227aab0dec2521be8042cf56855f7dc3a9fb14e08
)

prepare() {
    sed -i "s:sbin:bin:" Makefile
}

build() {
    mkdir .x86
    pushd .x86 > /dev/null

    shopt -s extglob
    cp -r ../* .
    make VERSION="$_tzver"

    popd > /dev/null

    make VERSION="$_tzver" CC=arm-linux-gnueabihf-cc
}

package() {
    pushd "${srcdir}" > /dev/null
    local zic=.x86/zic
    # install tzcode stuff
    make DESTDIR="${pkgdir}" zic="$zic" install
    # install license
    install -Dm644 LICENSE "${pkgdir}"/opt/usr/share/licenses/tzdata/LICENSE

    popd > /dev/null

    mv "${pkgdir}"/usr/{lib,share/man} "${pkgdir}"/opt/usr
    mv "${pkgdir}"/usr/{s,}bin "${pkgdir}"/opt

    install -D -m 644 -t "$pkgdir"/opt/share/zoneinfo "$srcdir"/iso3166.tab
    install -D -m 644 -t "$pkgdir"/opt/share/zoneinfo "$srcdir"/zone1970.tab

    # cleanup
    rm -rf "${pkgdir:?}"/{etc,usr}
}

configure() {
    add-bind-mount /home/root/.entware/share/zoneinfo \
        /usr/share/zoneinfo
}

postremove() {
    remove-bind-mount /usr/share/zoneinfo
}
