#!/usr/bin/env bash
# Copyright (c) 2022 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(yaft)
pkgdesc="Yet another framebuffer terminal"
url=https://github.com/timower/rM2-stuff/tree/master/apps/yaft
pkgver=0.0.7-2
timestamp=2021-05-02T09:23Z
maintainer="Mattéo Delabre <spam@delab.re>"
license=GPL-3.0
section="admin"
image=base:v2.3
installdepends=(display terminfo)

source=(
    https://github.com/timower/rM2-stuff/archive/refs/tags/v0.0.7.zip
    input.patch
    bash-l.patch
)

sha256sums=(
    df3c74e08c6f047be8cea3d50f9b84bf20a9191d9ee1850e9957146134dfef1c
    SKIP
    SKIP
)

build() {
    patch -u libs/rMlib/Device.cpp -i input.patch
    patch -u apps/yaft/main.cpp -i bash-l.patch
    mkdir build
    mkdir install
    cd build
    cmake -DCMAKE_TOOLCHAIN_FILE="/usr/share/cmake/$CHOST.cmake" \
        -DCMAKE_INSTALL_PREFIX="../install" -DCMAKE_BUILD_TYPE=Release ..
    cd apps/yaft
    make
    make install
}

package() {
    cp -r "$srcdir/install/." "$pkgdir"
}
