#!/usr/bin/env bash
# Copyright (c) 2022 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(yaft)
pkgdesc="Yet another framebuffer terminal"
url=https://github.com/timower/rM2-stuff/tree/master/apps/yaft
_tag=0.1.1
pkgver=${_tag}-1
timestamp=2023-08-12T14:31Z
maintainer="Mattéo Delabre <spam@delab.re>"
license=GPL-3.0
section="admin"
image=base:v2.3
installdepends=(display terminfo)

source=(
    "https://github.com/timower/rM2-stuff/archive/refs/tags/v${_tag}.zip"
    input.patch
)

sha256sums=(
    d6cafc2546feeda65412bf40778a669043fb98d83981edb1f55660bb999c2ccd
    SKIP
)

build() {
    patch -u libs/rMlib/Device.cpp -i input.patch
    mkdir build
    mkdir install
    cd build
    cmake -DCMAKE_TOOLCHAIN_FILE="/usr/share/cmake/$CHOST.cmake" \
        -DCMAKE_INSTALL_PREFIX="../install" -DCMAKE_BUILD_TYPE=Release ..
    cd apps/yaft
    make
    make install
    cd ../../libs/libYaft
    make install
}

package() {
    cp -r "$srcdir/install/." "$pkgdir"
}
