#!/usr/bin/env bash
# Copyright (c) 2023 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(move-logs-to-opt)
pkgdesc="Move log files to /opt to save space on the root partition"
url=https://github.com/toltec-dev/toltec
pkgver=0.0.1-1
timestamp=2024-01-07T23:55Z
section="utils"
maintainer="Eeems <eeems@eeems.email>"
license=MIT

package() {
    mkdir -p "$pkgdir"/opt/var/log
}

configure() {
    local source_path=/var/log
    local target_path="/home/root/.entware{$source_path}"
    local unit_name="$(systemd-escape --path "$source_path").mount"
    journalctl --sync --flush
    systemctl stop systemd-journald.service
    if ! unit-exists "$unit_name"; then
        echo "Moving log files to new location"
        mkdir -p "$target_path"
        mv -r "${source_path}/." "$target_path"
        rm -r "${source_path}/*"
    fi
    if [[ -e $unit_path ]]; then
        echo "Bind mount configuration for '${source_path}' already exists, updating"
    else
        echo "Mounting '${target_path}' over '${source_path}'"
    fi
    local unit_path="/lib/systemd/system/$unit_name"
    cat > "$unit_path" << UNIT
[Unit]
Description=Bind mount $1 over $2
DefaultDependencies=no
Conflicts=umount.target
Before=local-fs.target umount.target systemd-journald.service

[Mount]
What=${target_path}
Where=${source_path}
Type=none
Options=bind
UNIT
    systemctl daemon-reload
    systemctl enable "$unit_name"
    systemctl restart "$unit_name"
    systemctl start systemd-journald.service
}

postremove() {
    local bind_path
    local unit_name
    local unit_path
    bind_path=/var/log
    unit_name="$(systemd-escape --path "$bind_path").mount"
    unit_path="/lib/systemd/system/$unit_name"
    if [[ -e $unit_path ]]; then
        journalctl --sync --flush
        systemctl stop systemd-journald.service
        remove-bind-mount "$bind_path"
        systemctl start systemd-journald.service
    fi
}
