#!/usr/bin/env bash
# Copyright (c) 2021 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(xochitl)
pkgdesc="Read documents and take notes"
url=https://remarkable.com
pkgver=0.0.0-12
timestamp=2021-11-29T22:06Z
section="readers"
maintainer="Mattéo Delabre <spam@delab.re>"
license=MIT
installdepends=(findutils toltec-base)

source=(
    xochitl
    xochitl.png
    xochitl.draft
    xochitl.oxide
    toltec-wrapper.conf
    env-readme
)
sha256sums=(
    SKIP
    SKIP
    SKIP
    SKIP
    SKIP
    SKIP
)

package() {
    install -d "$pkgdir"/opt/etc/draft \
        "$pkgdir"/opt/etc/draft/icons \
        "$pkgdir"/opt/etc/xochitl.env.d \
        "$pkgdir"/etc/systemd/system/xochitl.service.d \
        "$pkgdir"/etc/systemd/system/remarkable-shutdown.service.d \
        "$pkgdir"/etc/systemd/system/remarkable-reboot.service.d

    install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/xochitl
    install -D -m 644 "$srcdir"/env-readme "$pkgdir"/opt/etc/xochitl.env.d/README

    install -D -m 644 -t "$pkgdir"/opt/etc/draft "$srcdir"/xochitl.draft
    install -D -m 644 -t "$pkgdir"/opt/etc/draft/icons "$srcdir"/xochitl.png
    install -D -m 644 -t "$pkgdir"/opt/usr/share/applications "$srcdir"/xochitl.oxide

    install -D -m 644 -t "$pkgdir"/etc/systemd/system/xochitl.service.d \
        "$srcdir"/toltec-wrapper.conf
    install -D -m 644 -t "$pkgdir"/etc/systemd/system/remarkable-shutdown.service.d \
        "$srcdir"/toltec-after-launcher.conf
    install -D -m 644 -t "$pkgdir"/etc/systemd/system/remarkable-reboot.service.d \
        "$srcdir"/toltec-after-launcher.conf
}

configure() {
    systemctl daemon-reload
}

postremove() {
    systemctl daemon-reload
}
