#!/usr/bin/env bash
# Copyright (c) 2020 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(xochitl)
pkgdesc="Read documents and take notes"
url=https://remarkable.com
pkgver=0.0.0-3
timestamp=2020-09-24T18:48Z
section="readers"
maintainer="Mattéo Delabre <spam@delab.re>"
license=Apache-2.0

source=(
    xochitl.png
    xochitl.draft
    xochitl.oxide
)
sha256sums=(
    SKIP
    SKIP
    SKIP
)

package() {
    install -d "$pkgdir"/opt/etc/draft "$pkgdir"/opt/etc/draft/icons
    install -D -m 644 -t "$pkgdir"/opt/etc/draft "$srcdir"/xochitl.draft
    install -D -m 644 -t "$pkgdir"/opt/etc/draft/icons "$srcdir"/xochitl.png
    install -D -m 644 -t "$pkgdir"/opt/usr/share/applications "$srcdir"/xochitl.oxide
}
