#!/usr/bin/env bash
# Copyright (c) 2021 The Toltec Contributors
# SPDX-License-Identifier: MIT

for file in /opt/etc/xochitl.env.d/*.env; do
    if [[ -r $file ]]; then
        echo "Sourcing $file"
        # shellcheck disable=SC1090
        source "$file"
    fi
done
exec /usr/bin/xochitl "$@"
