#!/usr/bin/env bash
# Copyright (c) 2021 The Toltec Contributors
# SPDX-License-Identifier: MIT

echo "Loading custom environment variables from /opt/etc/xochitl.env.d"
# shellcheck disable=SC2046
export $(grep -vh '^#' /opt/etc/xochitl.env.d/* | xargs -d '\n')
exec /usr/bin/xochitl "$@"
