#!/usr/bin/env bash
# Copyright (c) 2024 The Toltec Contributors
# SPDX-License-Identifier: MIT
pkgnames=(7zip)
pkgdesc="A file archiver with a high compression ratio"
url="https://www.7-zip.org/"
section="utils"
pkgver=23.01-2
timestamp=2023-06-20T00:00:00Z
maintainer="Eeems <eeems@eeems.email>"
license=LGPL-2.1-or-later
installdepends=(7-zip)

source=()
sha256sums=()

package() {
    ;
    ;
}
