#!/usr/bin/env bash
# Copyright (c) 2021 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(whiteboard-hypercard)
pkgdesc="Real-time collaboration, drawing or whiteboarding"
url=https://github.com/fenollp/reMarkable-tools
pkgver=0.3.4-1
timestamp=2021-10-25T15:45Z
section="drawing"
maintainer="Pierre Fenoll <pierrefenoll@gmail.com>"
license=Apache-2.0
installdepends=(display)
flags=(patch_rm2fb)

image=rust:v2.2
source=(
    https://github.com/fenollp/reMarkable-tools/archive/v0.3.4.zip
    whiteboard-hypercard.draft
)
sha256sums=(
    b343e1b4af9e0bf247ff2fab8331648ddd89941fb5c0ea9a45417d3bb4b20193
    SKIP
)

build() {
    cd marauder
    rustup component add rustfmt
    cargo build --release --bin whiteboard --locked
}

package() {
    install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/marauder/target/armv7-unknown-linux-gnueabihf/release/whiteboard
    install -D -m 644 -t "$pkgdir"/opt/etc/draft "$srcdir"/whiteboard-hypercard.draft
}
