#!/usr/bin/env bash
# Copyright (c) 2024 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(whiteboard-hypercard)
pkgdesc="Real-time collaboration, drawing or whiteboarding"
url=https://github.com/fenollp/reMarkable-tools
pkgver=0.4.0-1
timestamp=2024-05-14T23:01:16Z
section="drawing"
maintainer="Pierre Fenoll <pierrefenoll@gmail.com>"
license=CC-BY-NC-ND
installdepends=(display)
flags=(patch_rm2fb)

image=rust:v3.1
source=(
    https://github.com/fenollp/reMarkable-tools/archive/refs/tags/v0.4.0.zip
    whiteboard-hypercard.draft
)
sha256sums=(
    3184125c71b4d0a628280b0c49bb368a254dd582b951f5a62ca451c3dc465e65
    SKIP
)

build() {
    pushd marauder
    rustup component add rustfmt
    cargo fetch
    cargo build --release --bin whiteboard --locked --frozen --offline
    popd
}

package() {
    install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/marauder/target/armv7-unknown-linux-gnueabihf/release/whiteboard
    install -D -m 644 -t "$pkgdir"/opt/etc/draft "$srcdir"/whiteboard-hypercard.draft
}
