#!/usr/bin/env bash
# Copyright (c) 2021 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(neofetch)
pkgdesc="A command-line system information tool"
url="https://github.com/rM-self-serve/neofetch-rM"
pkgver=1.1.0-1
timestamp=2023-12-06T11:43:00Z
section="utils"
maintainer="rM-self-serve <122753594+rM-self-serve@users.noreply.github.com>"
license=MIT

source=(
    https://github.com/rM-self-serve/neofetch-rM/archive/955997e4e3b8be682f40ee54366e44337df68959.zip
)

sha256sums=(
    451017bd2517cf8c124af772e77b316ad784507709219e5831b28f613830f7e5
)

package() {
    install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/neofetch
}

postupgrade() {
    echo ""
    echo "You may choose to remove ~/.config/neofetch/config.conf"
    echo "in order to get the latest default config."
}
