#!/usr/bin/env bash
# Copyright (c) 2021 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(neofetch)
pkgdesc="A command-line system information tool"
url="https://github.com/rM-self-serve/neofetch-rM"
pkgver=0.0.0-1
timestamp=2023-02-09T11:43:00Z
section="utils"
maintainer="rM-self-serve <122753594+rM-self-serve@users.noreply.github.com>"
license=MIT

source=(
    https://github.com/rM-self-serve/neofetch-rM/archive/c497597ba4b481042cbb48b7c2c55e45dda25543.zip
)

sha256sums=(
    06492898eac6fb4f2cc95ca52c65f8f4f580ada57b4fe433722dabeae884b633
)

package() {
    install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/neofetch
}
