#!/usr/bin/env bash
# Copyright (c) 2020 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(appmarkable)
pkgdesc="Front-end for apps that do not have a graphical user interface"
url="https://github.com/LinusCDE/appmarkable"
pkgver=0.0.0-8
timestamp=2020-09-07T00:16Z
section="devel"
maintainer="Linus K. <linus@cosmos-ink.net>"
license=MIT

image=rust:v1.1
source=(https://github.com/LinusCDE/appmarkable/archive/b4226e896f441af9895ed5a4ff183af7f93b11ae.zip)
sha256sums=(0422cee28668d4e7ff554c26884e45ec63feff840eec92e6b8b2e8a7905a9d3b)

build() {
    rm -r .cargo/
    cargo build --release --target=armv7-unknown-linux-gnueabihf
}

package() {
    install -D -m 755 "$srcdir"/target/armv7-unknown-linux-gnueabihf/release/appmarkable "$pkgdir"/opt/bin/appmarkable
}
