#!/usr/bin/env bash
# Copyright (c) 2021 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(appmarkable)
pkgdesc="Front-end for apps that do not have a graphical user interface"
url="https://github.com/LinusCDE/appmarkable"
pkgver=0.1.2-1
timestamp=2024-05-30T22:19Z
section="devel"
maintainer="Linus K. <linus@cosmos-ink.net>"
license=MIT
installdepends=(display)
flags=(patch_rm2fb)

image=rust:v3.1
source=(https://github.com/LinusCDE/appmarkable/archive/ab02a4d3c29a8308b99e8b5ac1184f4d4ea5468a.zip)
sha256sums=(2ee2e95ee93c07fdbf8d7d553fc73c0545f64d2e6c78e2cb1045f78227364062)

build() {
    # Fall back to system-wide config
    rm .cargo/config
    cargo build --release --bin appmarkable
}

package() {
    install -D -m 755 -t "$pkgdir"/opt/bin \
        "$srcdir"/target/armv7-unknown-linux-gnueabihf/release/appmarkable
}
