#!/usr/bin/env bash
# Copyright (c) 2020 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(koreader)
pkgdesc="An ebook reader application supporting PDF, DjVu, EPUB, FB2 and many more formats"
url=https://github.com/koreader/koreader
pkgver=2020.12-2
timestamp=2020-10-10T20:13Z
section=readers
maintainer="raisjn <of.raisjn@gmail.com>"
license=AGPL-3.0-or-later
depends=(fbink fbdepth)

_srcver="v${pkgver%-*}"
source=(
    "https://build.koreader.rocks/download/stable/$_srcver/koreader-remarkable-$_srcver.zip"
    koreader.png
    koreader.draft
    koreader.oxide
)
sha256sums=(
    38db8f3895472828d7c1d63fc54db426135a8dbf8425633e299a1a9abfdb69b2
    SKIP
    SKIP
    SKIP
)

package() {
    install -d "$pkgdir"/opt/koreader
    cp -R "$srcdir"/* "$pkgdir"/opt/koreader/
    rm "$pkgdir"/opt/koreader/koreader*zip
    rm "$pkgdir"/opt/koreader/{fbink,fbdepth}
    ln -s /opt/bin/fbink "$pkgdir"/opt/koreader/fbink
    ln -s /opt/bin/fbdepth "$pkgdir"/opt/koreader/fbdepth

    install -D -m 644 -t "$pkgdir"/opt/etc/draft/ "$recipedir"/koreader.draft
    install -D -m 644 -t "$pkgdir"/opt/usr/share/applications/ "$recipedir"/koreder.oxide
    install -D -m 644 -t "$pkgdir"/opt/etc/draft/icons/ "$srcdir"/resources/koreader.png
    install -D -m 755 -t "$pkgdir"/opt/bin/ "$recipedir"/koreader
}

configure() {
    if systemctl --quiet is-active tarnish; then
        rot apps call reload
    fi
}
postremove() {
    # Check to see if tarnish is running and rot is available
    # shellcheck disable=SC2009
    if systemctl list-units --full -all | grep -Fq 'tarnish.service' || [[ "$(ps | grep tarnish | grep -v grep)" != "" ]]; then
        echo "You may need to manually remove the application entry for KOReader in Oxide."
    fi
}
