#!/usr/bin/env bash
# Copyright (c) 2020 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgname=koreader
pkgdesc="An ebook reader application supporting PDF, DjVu, EPUB, FB2 and many more formats"
url=https://github.com/koreader/koreader
pkgver=2020.09-53-1
timestamp=2020-10-09T06:43Z
section=readers
maintainer="raisjn <of.raisjn@gmail.com>"
license=AGPL-3.0-or-later

source=("https://build.koreader.rocks/download/nightly/v${pkgver%-[[:alnum:]]*}-gb8fa553_${timestamp:0:10}/koreader-remarkable-v${pkgver%-[[:alnum:]]*}-gb8fa553_${timestamp:0:10}.zip")
sha256sums=(51052d0f45617009aebbeb964c5c9ab4ab329dce710fa894715a94217db297d9)

package() {
    install -d "$pkgdir"/opt/koreader
    cp -R "$srcdir"/* "$pkgdir"/opt/koreader/
    rm "$pkgdir"/opt/koreader/koreader*zip

    install -D -m 644 -t "$pkgdir"/opt/etc/draft/ "$recipedir"/koreader.draft
    install -D -m 644 -t "$pkgdir"/opt/etc/draft/icons/ "$srcdir"/resources/koreader.png
    install -D -m 755 -t "$pkgdir"/opt/bin/ "$recipedir"/koreader
}

configure() {
    if systemctl list-units --full -all | grep -Fq "tarnish.service"; then
        echo "KOReader has an outstanding bug where it doesn't resize the screen properly when returning to Oxide. See Oxide's release notes for a workaround."
    fi
}
