#!/usr/bin/env bash
# Copyright (c) 2021 The Toltec Contributors
# SPDX-License-Identifier: MIT

_pkgname='signature-rm'
pkgnames=("$_pkgname")
pkgdesc="Remove the signature from the bottom of emails"
url="https://github.com/rM-self-serve/signature-rM"
pkgver=1.0.2-1
timestamp=2023-12-06T11:43:00Z
section="utils"
maintainer="rM-self-serve <122753594+rM-self-serve@users.noreply.github.com>"
license=MIT
image=rust:v3.1

source=(
    "$url"/archive/77eef2b421654d14d968f46c055392581e180b8e.zip
)
sha256sums=(
    60ac53d2f621dd8baabf0032b0c67fd46ad567fe5e512129396b39f4c697bc2e
)

build() {
    cargo build --release
}

package() {
    install -D -m 755 -t "$pkgdir"/opt/bin \
        "$srcdir/target/armv7-unknown-linux-gnueabihf/release/$_pkgname"
}

_restore() {
    if signature-rm is-applied > /dev/null 2>&1; then
        echo "Reverting /usr/bin/xochitl"
        if ! signature-rm revert --backup -y > /dev/null 2>&1; then
            if ! signature-rm revert --reverse -y > /dev/null 2>&1; then
                echo "Could not revert /usr/bin/xochitl"
            fi
        fi
        echo "Success"
    fi
}

preremove() {
    _restore
}

preupgrade() {
    _restore
}
