#!/usr/bin/env bash
# Copyright (c) 2020 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(remarkable-splash)
pkgdesc="Show splashscreens + remarkable-shutdown replacement that does not clear the screen"
url=https://github.com/ddvk/remarkable-splash
pkgver=1.0-3
timestamp=2019-12-31T10:07Z
section="utils"
maintainer="Eeems <eeems@eeems.email>"
license=MIT

image=qt:v1.1
source=(https://github.com/ddvk/remarkable-splash/archive/e6e0b1e1f3604ab99fb7b476cd290b19c5644025.zip)
sha256sums=(4aa3988707f9b66752ec9ec2f407cce2ac6e433ae7f06affea9f26957d206b4a)

build() {
    qmake
    make
}

package() {
    install -D -m 755 "$srcdir"/remarkable-splash "$pkgdir"/opt/bin/remarkable-splash
}
