#!/usr/bin/env bash

MEDIA_DIR=/home/root/plato-media/

# This directory should not be tracked by opkg
# so that its contents are kept after removing
if [ ! -d $MEDIA_DIR ]; then
    mkdir $MEDIA_DIR
    echo ""
    echo "Place your media for plato in '$MEDIA_DIR'"
    echo ""
fi
