#!/usr/bin/env bash
# Copyright (c) 2020 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(changescrn)
pkgdesc="Change sleep/suspend/poweroff/reboot screens"
url=https://github.com/pr0fsmith/rMscreens/
pkgver=1.0.0-1
timestamp=2022-03-15T01:28:33Z
section="utils"
maintainer="pr0fsmith <evon_smith@yahoo.ca>"
license=GPL-3.0

source=(https://github.com/pr0fsmith/rMscreens/archive/47c01faf51cbb8dd6a83c5a26e646ae246ee26f6.zip)
sha256sums=(47c01faf51cbb8dd6a83c5a26e646ae246ee26f6)

package() {
    install -Dm755 "$srcdir"/changescrn "$pkgdir/opt/bin/changescrn"
}
