#!/usr/bin/env bash
# Copyright (c) 2020 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(changescrn)
pkgdesc="Change sleep/suspend/poweroff/reboot screens"
url=https://github.com/pr0fsmith/rMscreens/
pkgver=1.0.0-1
timestamp=2022-03-15T01:28:33Z
section="utils"
maintainer="pr0fsmith <evon_smith@yahoo.ca>"
license=GPL-3.0

source=(https://github.com/pr0fsmith/rMscreens/archive/0775fa67ace15cfce85e07ceda38397dfcee8236.zip)
sha256sums=(7ecf9c5355a5f06a3424fe24b04e94fc458b93b83ca015e5700308f683d8c102)

package() {
    install -Dm755 "$srcdir"/changescrn "$pkgdir/opt/bin/changescrn"
}
