#!/usr/bin/env bash
# Copyright (c) 2020 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(yaft tilem)
pkgver=0.0.2-1
timestamp=2021-01-26T10:42Z
maintainer="None <none@example.com"
license=GPL-3.0

source=(
    https://github.com/timower/rM2-stuff/releases/download/v0.0.2/package.tar.gz
    yaft.png
    yaft.draft
    tilem.png
    tilem.draft
)

sha256sums=(
    d6bb2f354dd427e8b9440a9c9a2a37586d2bf3a93c6381b09abfe0d4d0d4623c
    SKIP
    SKIP
    SKIP
    SKIP
)

yaft() {
  pkgdesc="Yet another framebuffer terminal"
  url=https://github.com/timower/rM2-stuff/tree/master/apps/yaft
  section="admin"

  package() {
    install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/bin/yaft

    install -D -m 644 -t "$pkgdir"/opt/usr/share/terminfo/y "$srcdir"/etc/terminfo/y/yaft-256color

    install -D -m 644 -t "$pkgdir"/opt/etc/draft "$srcdir"/yaft.draft
    install -D -m 644 -t "$pkgdir"/opt/etc/draft/icons "$srcdir"/yaft.png
  }
}


tilem() {
  pkgdesc="TI-84+ emulator"
  url=https://github.com/timower/rM2-stuff/tree/master/apps/tilem
  section="util"

  package() {
    install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/bin/tilem

    install -D -m 644 -t "$pkgdir"/opt/etc/draft "$srcdir"/tilem.draft
    install -D -m 644 -t "$pkgdir"/opt/etc/draft/icons "$srcdir"/tilem.png
  }
}
