#!/usr/bin/env bash
# Copyright (c) 2020 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(wireguard-rm2)
pkgdesc="Fast, modern, secure VPN tunnel"
url=https://www.wireguard.com
pkgver=1.0.20201221
timestamp=2020-12-21T11:54Z
section=utils
maintainer="Jonah Weissman <jonahrweissman+toltec@gmail.com>"
license=GPL-2.0
depends=(wireguard-tools)
_kernelrev=d4e7e07a390f8b2544ca09d69142d18114149004
_defconfig=arch/arm/configs/zero-sugar_defconfig
_moddir=4.14.78

image=base:v1.2.1
source=(
    https://github.com/reMarkable/linux/archive/"$_kernelrev".tar.gz
    https://git.zx2c4.com/wireguard-linux-compat/snapshot/wireguard-linux-compat-"$pkgver".zip
)
sha256sums=(
    f05e5b2ef6875de739b9ec1a413968e8a31720a63a600de5c6e3300a925513e0
    c74cedb10c9b830d937b5575e4b7d2625a8534d2c06a80368e5530db23e69d3b
)

build() {
    apt-get update
    apt-get install -y bc lzop
    cp "$_defconfig" .config
    echo "CONFIG_NET_FOU=m" >> .config
    make olddefconfig
    make modules
    make modules_prepare

    # make wireguard.ko
    KERNELDIR=$(pwd) make -C src/
}

package() {
    export MOD_INSTALL_PATH=$pkgdir/lib/modules/$_moddir
    install -D "$srcdir/net/ipv4/udp_tunnel.ko" "$MOD_INSTALL_PATH/kernel/net/ipv4/udp_tunnel.ko"
    install -D "$srcdir/net/ipv6/ip6_udp_tunnel.ko" "$MOD_INSTALL_PATH/kernel/net/ipv6/ip6_udp_tunnel.ko"
    install -D "$srcdir/src/wireguard.ko" "$MOD_INSTALL_PATH/extra/wireguard.ko"
}

configure() {
    depmod -a
}
