#!/usr/bin/env bash
# Copyright (c) 2023 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(debian-chroot debootstrap)
section="utils"
# Each package has it's own timestamp override below
timestamp=2023-12-22T19:37Z
maintainer="Eeems <eeems@eeems.email>"
installdepends=(display)
flags=(nostrip)

source=(
    https://github.com/Eeems-org/remarkable-debian-chroot/archive/6f7ba5ca114bc416f53d646ba3bbe4f37050ae0e.zip
    https://salsa.debian.org/installer-team/debootstrap/-/archive/1.0.133/debootstrap-1.0.133.tar.gz
    debian-chroot.conf
)
sha256sums=(
    0612f909d9e58fc60f89967c27fb41db7c3536bf65fb019e0fb1cd5476deee2d
    734af3492eea99de940853e2c00e1a9ebd65c463362155f613aa24b9cc3336a0
    SKIP
)

debian-chroot() {
    pkgdesc="A minimal Debian chroot for the reMarkable tablet"
    url=https://github.com/Eeems-Org/remarkable-debian-chroot
    pkgver=0.0.0-1
    timestamp=2023-12-22T19:37Z
    license=MIT
    installdepends=(debootstrap lsof)
    package() {
        install -D -m 755 \
            "$srcdir"/bin/debian-chroot \
            "$pkgdir"/opt/bin/debian-chroot
        install -D -m 655 \
            "$srcdir"/debian-chroot.conf \
            "$pkgdir"/home/root/.config/debian-chroot.conf
        mkdir -p "$pkgdir"/opt/etc/
        ln -s /home/root/.config/debian-chroot.conf \
            "$pkgdir"/opt/etc/debian-chroot.conf
        source "$srcdir"/debian-chroot.conf
        mkdir -p "$pkgdir"/opt/lib/
        ln -s "$chroot_path" "$pkgdir"/opt/lib/debian-chroot
    }
    configure() {
        # Force debian chroot to install iteself
        debian-chroot true
    }
    preremove() {
        source /home/root/.config/debian-chroot.conf
        if lsof "$chroot_path"; then
            echo "Error: debian-chroot has running processes"
            exit 1
        fi
        umount -Rl "$chroot_path"
    }
    postremove() {
        source /home/root/.config/debian-chroot.conf
        rm -rf "$chroot_path"
        echo "Please reboot your system"
    }
}

debootstrap() {
    pkgdesc="debootstrap is a tool which will install a Debian base system into a subdirectory of another, already installed system."
    installdepends=(perl ar)
    url=https://wiki.debian.org/Debootstrap
    pkgver=1.0.133-1
    timestamp=2023-10-21T11:38Z
    license=MIT
    package() {
        cd "$srcdir"
        sed -i 's|/usr/sbin|/sbin|' Makefile
        make DESTDIR="$pkgdir"/opt install
        sed -i 's|DEBOOTSTRAP_DIR=/usr/share/debootstrap|DEBOOTSTRAP_DIR=/opt/usr/share/debootstrap|' "$pkgdir"/opt/sbin/debootstrap
    }
}
