#!/usr/bin/env bash
# Copyright (c) 2023 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(debian-chroot debootstrap)
section="utils"
# Each package has it's own timestamp override below
timestamp=2023-12-22T19:37Z
maintainer="Eeems <eeems@eeems.email>"
installdepends=(display)
flags=(nostrip)

source=(
    https://github.com/Eeems-org/remarkable-debian-chroot/archive/3ea18ec34cd5e720ec3959c68dcb10a390f6f864.zip
    https://salsa.debian.org/installer-team/debootstrap/-/archive/1.0.133/debootstrap-1.0.133.tar.gz
    debian-chroot.conf
)
sha256sums=(
    7ba890b00af5f2d8b15aec395acf8db0ca591794303d5e49e19455039b808a9f
    734af3492eea99de940853e2c00e1a9ebd65c463362155f613aa24b9cc3336a0
    SKIP
)

debian-chroot() {
    pkgdesc="A minimal Debian chroot for the reMarkable tablet"
    url=https://github.com/Eeems-Org/remarkable-debian-chroot
    pkgver=0.0.0-1
    timestamp=2023-12-22T19:37Z
    license=MIT
    installdepends=(debootstrap lsof)
    package() {
        install -D -m 755 \
            "$srcdir"/bin/debian-chroot \
            "$pkgdir"/opt/bin/debian-chroot
        install -D -m 655 \
            "$srcdir"/debian-chroot.conf \
            "$pkgdir"/home/root/.config/debian-chroot.conf
        mkdir -p "${pkgdir}/opt/lib/debian-chroot"
    }
    configure() {
        # Force debian chroot to install iteself
        debian-chroot true
    }
    preremove() {
        if lsof /opt/lib/debian-chroot; then
            echo "Error: debian-chroot has running processes"
            exit 1
        fi
        if ! grep -q /opt/lib/debian-chroot /proc/mounts; then
            echo "debian-chroot is not mounted"
            exit 0
        fi
        do_umount() {
            mp=$1
            shift
            if mountpoint -q $mp; then
                /bin/umount "$@" $mp
            fi
        }
        echo "Unmounting debian-chroot"
        do_umount /opt/lib/debian-chroot/mnt/remarkable/opt
        do_umount /opt/lib/debian-chroot/mnt/remarkable/home
        do_umount /opt/lib/debian-chroot/mnt/remarkable/var/lib/uboot
        do_umount /opt/lib/debian-chroot/mnt/remarkable
        do_umount /opt/lib/debian-chroot/var/volatile
        do_umount /opt/lib/debian-chroot/tmp
        do_umount /opt/lib/debian-chroot/run
        do_umount /opt/lib/debian-chroot/sys -l
        do_umount /opt/lib/debian-chroot/proc
        do_umount /opt/lib/debian-chroot/dev -l
        do_umount /opt/lib/debian-chroot
    }
    postremove() {
        rm -rf /opt/lib/debian-chroot
    }
}

debootstrap() {
    pkgdesc="debootstrap is a tool which will install a Debian base system into a subdirectory of another, already installed system."
    installdepends=(perl ar)
    url=https://wiki.debian.org/Debootstrap
    pkgver=1.0.133-1
    timestamp=2023-10-21T11:38Z
    license=MIT
    package() {
        cd "$srcdir"
        sed -i 's|/usr/sbin|/sbin|' Makefile
        make DESTDIR="$pkgdir"/opt install
        sed -i 's|DEBOOTSTRAP_DIR=/usr/share/debootstrap|DEBOOTSTRAP_DIR=/opt/usr/share/debootstrap|' "$pkgdir"/opt/sbin/debootstrap
    }
}
