#!/usr/bin/env bash
pkgname=remux
pkgdesc="App launcher that supports multi-tasking applications"
url="https://rmkit.dev/apps/remux"
pkgver=0.0.1-19
timestamp=2020-10-05T01:41+00:00
section=launchers
maintainer="raisjn <of.rajsn@gmail.com>"
license=MIT

image=python:v1.1
source=(
    https://github.com/rmkit-dev/rmkit/archive/8e56c61385fa5da73fbe4aefa1d7991ab82dfb89.zip
    remux.service
)
sha256sums=(
    b921b0c826475859e7f9c2a80d0bdc683d6cd9e0f315a97c554d1c3b2d064677
    SKIP
)

build() {
    pip3 install okp
    make remux
}

package() {
    install -d "$pkgdir"/opt/usr/bin
    install -D -m 755 "$srcdir"/src/build/remux "$pkgdir"/opt/bin/remux
    install -D -m 644 "$srcdir"/remux.service "$pkgdir"/lib/systemd/system/remux.service
}

configure() {
    systemctl daemon-reload

    if ! is-enabled "$pkgname.service"; then
        echo ""
        echo "Run the following command(s) to use $pkgname as your launcher"
        how-to-enable "$pkgname.service"
        echo ""
    fi
}

preremove() {
    echo "Disabling $pkgname"
    systemctl disable --now "$pkgname"
}

postremove() {
    systemctl daemon-reload
}
