#!/usr/bin/env bash
# Copyright (c) 2020 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(folly)
pkgdesc="Z-machine interpreter for interactive fiction"
url="https://github.com/bkirwi/folly"
pkgver=0.0.1-5
timestamp=2022-04-18T17:50:16Z
section=games
maintainer="Ben Kirwin <ben@kirw.in>"
license=MIT
installdepends=(display)
makedepends=(build:libclang-13-dev build:clang-13 build:llvm-13-dev)

image=rust:v3.3

# Whitespace-separated list of source archives that are needed to build the package
source=(
    https://github.com/bkirwi/folly/archive/97f5813086a9adabb70114b12aa5a2073458bc91.zip
    folly.draft
)
# SHA-256 checksums of the source archives above
sha256sums=(
    0d8f254660b760a5f4a6361b4c1bd2afa008274a2bcaf5838b3561f219954259
    SKIP
)

build() {
    local cpp_includes
    local gcc_version
    gcc_version="$("$CROSS_COMPILE"gcc -dumpfullversion)"
    cpp_includes="$(realpath "$SYSROOT"/../include/c++/"$gcc_version")"

    # Arguments for bindgen's usage of clang
    export BINDGEN_EXTRA_CLANG_ARGS="--sysroot=$SYSROOT -I$cpp_includes \
        -I$cpp_includes/$NGCONFIG"

    # Arguments for the gcc-based tensorflow build in the build.rs file of tflite-rs.
    export TFLITE_RS_MAKE_TARGET_TOOLCHAIN_PREFIX="$CROSS_COMPILE"
    export TFLITE_RS_MAKE_EXTRA_CFLAGS="$BINDGEN_EXTRA_CLANG_ARGS \
        -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a9"

    cargo build --release

    # Save the build system the trouble of stripping unused binaries
    rm -r target/release/build
    rm -r target/*/release/build
}

package() {
    # Install the app binary and the draft file
    install -D -m 755 "$srcdir"/target/*/release/folly "$pkgdir"/opt/bin/folly
    install -D -m 644 "$srcdir"/folly.draft "$pkgdir"/opt/etc/draft/folly.draft
}
