#!/usr/bin/env bash
# Copyright (c) 2020 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(tilem)
pkgdesc="TI-84+ calculator emulator"
url=https://github.com/timower/rM2-stuff/tree/master/apps/tilem
pkgver=0.1.1-1
timestamp=2023-11-25T20:49:48Z
maintainer="Mattéo Delabre <spam@delab.re>"
license=GPL-3.0
section="utils"
image=base:v3.1
installdepends=(display)

source=(https://github.com/timower/rM2-stuff/archive/refs/tags/v0.1.1.tar.gz)
sha256sums=(d6cafc2546feeda65412bf40778a669043fb98d83981edb1f55660bb999c2ccd)

build() {
    mkdir build
    mkdir install
    cd build
    cmake -DCMAKE_TOOLCHAIN_FILE="/usr/share/cmake/$CHOST.cmake" \
        -DCMAKE_INSTALL_PREFIX="../install" -DCMAKE_BUILD_TYPE=Release ..
    cd apps/tilem
    make
    make install
}

package() {
    cp -r "$srcdir/install/." "$pkgdir"
}
