#!/usr/bin/env bash
# Copyright (c) 2021 The Toltec Contributors
# SPDX-License-Identifier: MIT

archs=(rm1 rm2)
pkgnames=(ddvk-hacks)
pkgdesc="Enhance Xochitl with additional features"
url=https://github.com/ddvk/remarkable-hacks
pkgver=26.02-1
timestamp=2021-10-07T19:30:24Z
section="readers"
maintainer="Mattéo Delabre <spam@delab.re>"
license=MIT
flags=(nostrip)

source=(https://github.com/ddvk/remarkable-hacks/archive/60003434cc2fe5b5cbb825eef604bbd9ee46cda4.zip)
sha256sums=(7c8031c3942641910c8a6e55c61f3a074cf14c3787674e01183a13b2f5955976)

_patches_dir="/opt/share/ddvk-hacks"
_xochitl_path="/usr/bin/xochitl"
_work_dir="/home/root/.local/share/ddvk-hacks"
_backup_path="$_work_dir/xochitl.backup"
_old_backup_path="$_backup_path.old"
_patched_path="$_work_dir/xochitl.patched"

package() {
    if [[ $arch = rm1 ]]; then
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/26171_rm1/patch_19.1.02
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/26275_rm1/patch_20.1.03
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/27051_rm1/patch_21.1.04
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/28098_rm1/patch_23.1.02
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/291236_rm1/patch_24.1.02
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/2100324_rm1/patch_25.1.02
    elif [[ $arch = rm2 ]]; then
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/26171_rm2/patch_19.2.02
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/26275_rm2/patch_20.2.03
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/27051_rm2/patch_21.2.05
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/27153_rm2/patch_22.2.01
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/28098_rm2/patch_23.2.02
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/291217_rm2/patch_24.2.04
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/2100324_rm2/patch_25.2.01
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/2101332_rm2/patch_26.2.02
    fi
}

configure() {
    local build_date
    build_date="$(cat /etc/version)"
    local patch_version
    local device
    local original_hash
    local xochitl_version
    if [[ $arch = rm1 ]]; then
        device="reMarkable 1"
        case "$build_date" in
            "20210923152158")
                patch_version="25.1.02"
                original_hash="635917603b0d9349ddf5f6ead818701a42979945"
                xochitl_version="2.10.0.324"
                ;;
            "20210820111232")
                patch_version="24.1.02"
                original_hash="e5d3ce51e81a6e23bac0c66549b809e6dd4e35a0"
                xochitl_version="2.9.1.236"
                ;;
            "20210611154039")
                patch_version="23.1.02"
                original_hash="b688b4afbd5c13347bada20f26b9108d82658f9a"
                xochitl_version="2.8.0.98"
                ;;
            "20210504114855")
                patch_version="21.1.04"
                original_hash="123877bb7dd6133f4540e03d3912b1d4c4d76050"
                xochitl_version="2.7.0.51"
                ;;
            "20210322075617")
                patch_version="20.1.03"
                original_hash="50a44683ac1b8ce524e55e10f57b699e7c4ca409"
                xochitl_version="2.6.2.75"
                ;;
            "20210311193614")
                patch_version="19.1.02"
                original_hash="2d31db3e7f1a7b98a493cc5a1351fe303f849cd3"
                xochitl_version="2.6.1.71"
                ;;
            *)
                echo
                echo "Error: The version the device is running is not supported, yet."
                echo "Build date: $build_date"
                echo
                exit 1
                ;;
        esac
    elif [[ $arch = rm2 ]]; then
        device="reMarkable 2"
        case "$build_date" in
            "20210929140057")
                patch_version="26.2.02"
                original_hash="44ed43a128c821988519c3ea92c4516f011edd7e"
                xochitl_version="2.10.1.332"
                ;;
            "20210923144714")
                patch_version="25.2.01"
                original_hash="0990b599d412a1c6368985d872383b29b47ffab6"
                xochitl_version="2.10.0.324"
                ;;
            "20210812195523")
                patch_version="24.2.04"
                original_hash="ab37e201e819e4212fb4e2ce92cd747614499fbb"
                xochitl_version="2.9.1.217"
                ;;
            "20210611153600")
                patch_version="23.2.02"
                original_hash="02a851bc33231fcd253eee781eb127e3c942da69"
                xochitl_version="2.8.0.98"
                ;;
            "20210511153632")
                patch_version="22.2.01"
                original_hash="f0846772da9b810aecc2a307ba5dae21c072674a"
                xochitl_version="2.7.1.53"
                ;;
            "20210504114631")
                patch_version="21.2.05"
                original_hash="f0846772da9b810aecc2a307ba5dae21c072674a"
                xochitl_version="2.7.0.51"
                ;;
            "20210322075357")
                patch_version="20.2.03"
                original_hash="7b314d6fb03c8789396f0ed43a4b27a18c649d2d"
                xochitl_version="2.6.2.75"
                ;;
            "20210311194323")
                patch_version="19.2.02"
                original_hash="fc434bf45f1ff927af799ddccc7b2b0449f516f7"
                xochitl_version="2.6.1.71"
                ;;
            *)
                echo
                echo "Error: The version the device is running is not supported, yet."
                echo "Build date: $build_date"
                echo
                exit 1
                ;;
        esac
    else
        echo
        echo "Error: The architecture the device is running is not supported, yet."
        echo "Build date: $build_date"
        echo
        exit 1
    fi

    echo
    echo "Device: $device"
    echo "Xochitl version: $xochitl_version"
    echo "Patch version: $patch_version"
    echo

    if ! sha1sum -c <(echo "$original_hash  $_xochitl_path") > /dev/null 2>&1; then
        echo "Error: Invalid Xochitl checksum"
        echo "Maybe ddvk-hacks are already installed?"
        echo
        exit 1
    fi

    if [[ -f "$_backup_path" ]]; then
        mv "$_backup_path" "$_old_backup_path"
    fi

    mkdir -p "$(dirname "$_backup_path")"
    cp "$_xochitl_path" "$_backup_path"

    echo "Patching Xochitl"
    bspatch "$_backup_path" "$_patched_path" "$_patches_dir"/patch_"$patch_version"
    cp "$_patched_path" "$_xochitl_path"
    rm -rf /home/root/.cache/remarkable/xochitl/qmlcache/*

    echo "Please restart Xochitl to use the patches"
    echo
}

_restore() {
    echo
    echo "Restoring the original Xochitl binary"

    if ! diff "$_xochitl_path" "$_patched_path" > /dev/null 2>&1; then
        echo "Warning: Xochitl binary has changed!"
        echo "Not restoring the backup"
    else
        cp "$_backup_path" "$_xochitl_path"
        rm -rf /home/root/.cache/remarkable/xochitl/qmlcache/*
    fi

    echo
}

preremove() {
    _restore
}

preupgrade() {
    _restore
}
