#!/usr/bin/env bash
# Copyright (c) 2021 The Toltec Contributors
# SPDX-License-Identifier: MIT

archs=(rm1 rm2)
pkgnames=(ddvk-hacks)
pkgdesc="Enhance Xochitl with additional features"
url=https://github.com/ddvk/remarkable-hacks
pkgver=31.01-1
timestamp=2022-03-27T18:15:12Z
section="readers"
maintainer="Mattéo Delabre <spam@delab.re>"
license=MIT
flags=(nostrip)

source=(https://github.com/ddvk/remarkable-hacks/archive/593556fd5811a81f56d9fef94ca9fd75a3c52f67.zip)
sha256sums=(931e5b5f3f3c887b7432a5a8343598b66a2466b2c66716676987c6adf7f3cb7a)

_patches_dir="/opt/share/ddvk-hacks"
_xochitl_path="/usr/bin/xochitl"
_work_dir="/home/root/.local/share/ddvk-hacks"
_backup_path="$_work_dir/xochitl.backup"
_old_backup_path="$_backup_path.old"
_patched_path="$_work_dir/xochitl.patched"

package() {
    if [[ $arch = rm1 ]]; then
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/26171_rm1/patch_19.1.02
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/26275_rm1/patch_20.1.03
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/27051_rm1/patch_21.1.04
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/28098_rm1/patch_23.1.02
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/291236_rm1/patch_24.1.02
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/2100324_rm1/patch_25.1.03
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/2102356_rm1/patch_27.1.03
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/2103379_rm1/patch_28.1.02
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/2110442_rm1/patch_29.1.02
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/2121527_rm1/patch_30.1.08
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/2122573_rm1/patch_31.1.01
    elif [[ $arch = rm2 ]]; then
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/26171_rm2/patch_19.2.02
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/26275_rm2/patch_20.2.03
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/27051_rm2/patch_21.2.05
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/27153_rm2/patch_22.2.01
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/28098_rm2/patch_23.2.02
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/291217_rm2/patch_24.2.04
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/2100324_rm2/patch_25.2.01
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/2101332_rm2/patch_26.2.02
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/2102356_rm2/patch_27.2.05
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/2103379_rm2/patch_28.2.02
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/2110442_rm2/patch_29.2.02
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/2121527_rm2/patch_30.2.07
        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/2122573_rm2/patch_31.2.01
    fi
}

configure() {
    local build_date
    build_date="$(cat /etc/version)"
    local patch_version
    local device
    local original_hash
    local xochitl_version
    if [[ $arch = rm1 ]]; then
        device="reMarkable 1"
        case "$build_date" in
            "20220303122245")
                patch_version="31.1.01"
                original_hash="00b5095022a48e48cdbe435b8afff0e3dc736b96"
                xochitl_version="2.12.2.573"
                ;;
            "20220202133055")
                patch_version="30.1.08"
                original_hash="c542ee591b45cb18599dc852cc0d3ce82ec86b56"
                xochitl_version="2.12.1.527"
                ;;
            "20211208080907")
                patch_version="29.1.02"
                original_hash="1f72eb42b0745d40196cb7fece6a8fee55f958c0"
                xochitl_version="2.11.0.442"
                ;;
            "20211102142308")
                patch_version="28.1.02"
                original_hash="1978c56c0bf9a53e74fb05b7212381543adb709e"
                xochitl_version="2.10.3.379"
                ;;
            "20211014150444")
                patch_version="27.1.03"
                original_hash="a76509107656c03e866ec169ad317da9111f71be"
                xochitl_version="2.10.2.356"
                ;;
            "20210923152158")
                patch_version="25.1.03"
                original_hash="635917603b0d9349ddf5f6ead818701a42979945"
                xochitl_version="2.10.0.324"
                ;;
            "20210820111232")
                patch_version="24.1.02"
                original_hash="e5d3ce51e81a6e23bac0c66549b809e6dd4e35a0"
                xochitl_version="2.9.1.236"
                ;;
            "20210611154039")
                patch_version="23.1.02"
                original_hash="b688b4afbd5c13347bada20f26b9108d82658f9a"
                xochitl_version="2.8.0.98"
                ;;
            "20210504114855")
                patch_version="21.1.04"
                original_hash="123877bb7dd6133f4540e03d3912b1d4c4d76050"
                xochitl_version="2.7.0.51"
                ;;
            "20210322075617")
                patch_version="20.1.03"
                original_hash="50a44683ac1b8ce524e55e10f57b699e7c4ca409"
                xochitl_version="2.6.2.75"
                ;;
            "20210311193614")
                patch_version="19.1.02"
                original_hash="2d31db3e7f1a7b98a493cc5a1351fe303f849cd3"
                xochitl_version="2.6.1.71"
                ;;
            *)
                echo
                echo "Error: The version the device is running is not supported, yet."
                echo "Build date: $build_date"
                echo
                exit 1
                ;;
        esac
    elif [[ $arch = rm2 ]]; then
        device="reMarkable 2"
        case "$build_date" in
            "20220303120824")
                patch_version="31.2.01"
                original_hash="7105e311df4df7f4ccde457ce574da63f49d3a4e"
                xochitl_version="2.12.2.573"
                ;;
            "20220202133838")
                patch_version="30.2.07"
                original_hash="8728cf8a2677a1b458f8e1ed665f8c1358568f7f"
                xochitl_version="2.12.1.527"
                ;;
            "20211208075454")
                patch_version="29.2.02"
                original_hash="ad88de508a3c7da7f1ff6a9d394806c5d987026d"
                xochitl_version="2.11.0.442"
                ;;
            "20211102143141")
                patch_version="28.2.02"
                original_hash="8510d6f4380b6155d630baecaccccfb0147263d0"
                xochitl_version="2.10.3.379"
                ;;
            "20211014151303")
                patch_version="27.2.05"
                original_hash="2cc077e0bc5eca53664d4692197d54b477fa02ba"
                xochitl_version="2.10.2.356"
                ;;
            "20210929140057")
                patch_version="26.2.02"
                original_hash="44ed43a128c821988519c3ea92c4516f011edd7e"
                xochitl_version="2.10.1.332"
                ;;
            "20210923144714")
                patch_version="25.2.01"
                original_hash="0990b599d412a1c6368985d872383b29b47ffab6"
                xochitl_version="2.10.0.324"
                ;;
            "20210812195523")
                patch_version="24.2.04"
                original_hash="ab37e201e819e4212fb4e2ce92cd747614499fbb"
                xochitl_version="2.9.1.217"
                ;;
            "20210611153600")
                patch_version="23.2.02"
                original_hash="02a851bc33231fcd253eee781eb127e3c942da69"
                xochitl_version="2.8.0.98"
                ;;
            "20210511153632")
                patch_version="22.2.01"
                original_hash="f0846772da9b810aecc2a307ba5dae21c072674a"
                xochitl_version="2.7.1.53"
                ;;
            "20210504114631")
                patch_version="21.2.05"
                original_hash="f0846772da9b810aecc2a307ba5dae21c072674a"
                xochitl_version="2.7.0.51"
                ;;
            "20210322075357")
                patch_version="20.2.03"
                original_hash="7b314d6fb03c8789396f0ed43a4b27a18c649d2d"
                xochitl_version="2.6.2.75"
                ;;
            "20210311194323")
                patch_version="19.2.02"
                original_hash="fc434bf45f1ff927af799ddccc7b2b0449f516f7"
                xochitl_version="2.6.1.71"
                ;;
            *)
                echo
                echo "Error: The version the device is running is not supported, yet."
                echo "Build date: $build_date"
                echo
                exit 1
                ;;
        esac
    else
        echo
        echo "Error: The architecture the device is running is not supported, yet."
        echo "Build date: $build_date"
        echo
        exit 1
    fi

    echo
    echo "Device: $device"
    echo "Xochitl version: $xochitl_version"
    echo "Patch version: $patch_version"
    echo

    if ! sha1sum -c <(echo "$original_hash  $_xochitl_path") > /dev/null 2>&1; then
        echo "Error: Invalid Xochitl checksum"
        echo "Maybe ddvk-hacks are already installed?"
        echo
        exit 1
    fi

    if [[ -f "$_backup_path" ]]; then
        mv "$_backup_path" "$_old_backup_path"
    fi

    mkdir -p "$(dirname "$_backup_path")"
    cp "$_xochitl_path" "$_backup_path"

    echo "Patching Xochitl"
    bspatch "$_backup_path" "$_patched_path" "$_patches_dir"/patch_"$patch_version"
    cp "$_patched_path" "$_xochitl_path"
    rm -rf /home/root/.cache/remarkable/xochitl/qmlcache/*

    echo "Please restart Xochitl to use the patches"
    echo
}

_restore() {
    echo
    echo "Restoring the original Xochitl binary"

    if ! diff "$_xochitl_path" "$_patched_path" > /dev/null 2>&1; then
        echo "Warning: Xochitl binary has changed!"
        echo "Not restoring the backup"
    else
        cp "$_backup_path" "$_xochitl_path"
        rm -rf /home/root/.cache/remarkable/xochitl/qmlcache/*
    fi

    echo
}

preremove() {
    _restore
}

preupgrade() {
    _restore
}
