#!/usr/bin/env bash
# Copyright (c) 2021 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(ddvk-hacks)
pkgdesc="Enhance Xochitl with additional features"
url=https://github.com/ddvk/remarkable-hacks
pkgver=18.01-1
timestamp=2020-12-25T14:32Z
section="readers"
maintainer="Mattéo Delabre <spam@delab.re>"
license=MIT
flags=(nostrip)

source=(https://github.com/ddvk/remarkable-hacks/archive/28e45da6cf399770669ca928ad05fa3fbfe22592.zip)
sha256sums=(447a4364e2ae26a70ad1fd5c5dc94e5484c69a7e43ed427829034f7f8eec7655)

_patches_dir="/opt/share/ddvk-hacks"
_xochitl_path="/usr/bin/xochitl"
_work_dir="/home/root/.local/share/ddvk-hacks"
_backup_path="$_work_dir/xochitl.backup"
_old_backup_path="$_backup_path.old"
_patched_path="$_work_dir/xochitl.patched"

package() {
    install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/26171_rm1/patch_19.1.02
    install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/26171_rm2/patch_19.2.02
    install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/26275_rm1/patch_20.1.03
    install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/26275_rm2/patch_20.2.03
    install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/27051_rm1/patch_21.1.04
    install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/27051_rm2/patch_21.2.05
    install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/27153_rm2/patch_22.2.01
    install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/28098_rm1/patch_23.1.02
    install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/28098_rm2/patch_23.2.02
}

configure() {
    local build_date
    build_date="$(cat /etc/version)"
    local patch_version
    local device
    local original_hash
    local xochitl_version

    case "$build_date" in
        "20210611153600")
            patch_version="23.2.02"
            device="reMarkable 2"
            original_hash="02a851bc33231fcd253eee781eb127e3c942da69"
            xochitl_version="2.8.0.98"
            ;;
        "20210611154039")
            patch_version="23.2.02"
            device="reMarkable 1"
            original_hash="b688b4afbd5c13347bada20f26b9108d82658f9a"
            xochitl_version="2.8.0.98"
            ;;
        "20210511153632")
            patch_version="22.2.01"
            device="reMarkable 2"
            original_hash="f0846772da9b810aecc2a307ba5dae21c072674a"
            xochitl_version="2.7.1.53"
            ;;
        "20210504114631")
            patch_version="21.2.05"
            device="reMarkable 2"
            original_hash="f0846772da9b810aecc2a307ba5dae21c072674a"
            xochitl_version="2.7.0.51"
            ;;
        "20210504114855")
            patch_version="21.1.04"
            device="reMarkable 1"
            original_hash="123877bb7dd6133f4540e03d3912b1d4c4d76050"
            xochitl_version="2.7.0.51"
            ;;
        "20210322075357")
            patch_version="20.2.03"
            device="reMarkable 2"
            original_hash="7b314d6fb03c8789396f0ed43a4b27a18c649d2d"
            xochitl_version="2.6.2.75"
            ;;
        "20210322075617")
            patch_version="20.1.03"
            device="reMarkable 1"
            original_hash="50a44683ac1b8ce524e55e10f57b699e7c4ca409"
            xochitl_version="2.6.2.75"
            ;;
        "20210311194323")
            patch_version="19.2.02"
            device="reMarkable 2"
            original_hash="fc434bf45f1ff927af799ddccc7b2b0449f516f7"
            xochitl_version="2.6.1.71"
            ;;
        "20210311193614")
            patch_version="19.1.02"
            device="reMarkable 1"
            original_hash="2d31db3e7f1a7b98a493cc5a1351fe303f849cd3"
            xochitl_version="2.6.1.71"
            ;;
        *)
            echo
            echo "Error: The version the device is running is not supported, yet."
            echo "Build date: $build_date"
            echo
            exit 1
            ;;
    esac

    echo
    echo "Device: $device"
    echo "Xochitl version: $xochitl_version"
    echo "Patch version: $patch_version"
    echo

    if ! sha1sum -c <(echo "$original_hash  $_xochitl_path") > /dev/null 2>&1; then
        echo "Error: Invalid Xochitl checksum"
        echo "Maybe ddvk-hacks are already installed?"
        echo
        exit 1
    fi

    if [[ -f "$_backup_path" ]]; then
        mv "$_backup_path" "$_old_backup_path"
    fi

    mkdir -p "$(dirname "$_backup_path")"
    cp "$_xochitl_path" "$_backup_path"

    echo "Patching Xochitl"
    bspatch "$_backup_path" "$_patched_path" "$_patches_dir"/patch_"$patch_version"
    cp "$_patched_path" "$_xochitl_path"
    rm -rf /home/root/.cache/remarkable/xochitl/qmlcache/*

    echo "Please restart Xochitl to use the patches"
    echo
}

_restore() {
    echo
    echo "Restoring the original Xochitl binary"

    if ! diff "$_xochitl_path" "$_patched_path" > /dev/null 2>&1; then
        echo "Warning: Xochitl binary has changed!"
        echo "Not restoring the backup"
    else
        cp "$_backup_path" "$_xochitl_path"
        rm -rf /home/root/.cache/remarkable/xochitl/qmlcache/*
    fi

    echo
}

preremove() {
    _restore
}

preupgrade() {
    _restore
}
