#!/usr/bin/env bash
# Copyright (c) 2020 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(harmony)
pkgdesc="Procedural sketching app"
url="https://rmkit.dev/apps/harmony"
pkgver=0.0.1-16
timestamp=2020-10-05T01:41+00:00
section=drawing
maintainer="raisjn <of.raisjn@gmail.com>"
license=MIT
conflicts=(rmkit)

image=python:v1.1
source=(https://github.com/rmkit-dev/rmkit/archive/8e56c61385fa5da73fbe4aefa1d7991ab82dfb89.zip)
sha256sums=(b921b0c826475859e7f9c2a80d0bdc683d6cd9e0f315a97c554d1c3b2d064677)

build() {
    pip3 install okp
    make -j"$(nproc)" harmony
}

package() {
    install -d "$pkgdir"/opt/bin
    install -D -m 755 "$srcdir"/src/build/harmony "$pkgdir"/opt/bin/harmony

    mkdir -p "$pkgdir"/opt/etc/draft/
    install -D -m 644 "$srcdir"/src/harmony/harmony.draft "$pkgdir"/opt/etc/draft/harmony.draft
}

configure() {
    mkdir -p /home/root/harmony
}
