#!/usr/bin/env bash
# Copyright (c) 2023 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(toltec-python)
pkgdesc="Python is a programming language that lets you work quickly and integrate systems more effectively."
url="https://python.org"
_ver=3.12.1
pkgver=${_ver}-1
timestamp=2023-12-08T00:00Z
section=utils
maintainer="Eeems <eeems@eeems.email>"
license=PSF-2.0

image=python:v3.1
source=(
    "https://www.python.org/ftp/python/${_ver}/Python-${_ver}.tar.xz"
)
sha256sums=(
    8dfb8f426fcd226657f9e2bd5f1e96e53264965176fa17d32658e873591aeb21
)
makedepends=("build:python${_ver%.*}")

build() {
    ./configure \
        --enable-optimizations \
        --with-lto \
        --prefix=/opt \
        --build="$(./config.guess)" \
        --host="$CHOST" \
        --with-build-python="$(which "python${_ver%.*}")" \
        --with-ensurepip=no \
        ac_cv_buggy_getaddrinfo=no \
        ac_cv_file__dev_ptmx=yes \
        ac_cv_file__dev_ptc=no
    make --jobs="$(nproc)"
    make DESTDIR=dist altinstall
}

package() {
    cd "$srcdir"
    cp -ar dist/. "$pkgdir"
}

configure() {
    /opt/bin/python3.12 -m ensurepip --upgrade --altinstall
}
