#!/usr/bin/env bash
# Copyright (c) 2020 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(zshelf)
pkgdesc="Z-Library browser and downloader"
url=https://github.com/khanhas/zshelf
pkgver=0.1.1-1
section=utils
timestamp=2021-01-31T05:25Z
maintainer="khanhas <xuankhanh963@gmail.com>"
license=GPL-3.0
depends=(node)

source=(
    https://github.com/khanhas/zshelf/archive/v0.1.1.zip
    zshelf.draft
    zshelf.png
)
sha256sums=(
    c6bc1980c90e8ea05149f3bd609667edba4e8465f9db0f6882407ca4dc70e120
    SKIP
    SKIP
)

image=qt:v1.1
build() {
    qmake zshelf.pro
    make

    # Get needed build packages
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -y
    apt-get install -y \
        --no-install-recommends \
        -o Dpkg::Options::="--force-confdef" \
        nodejs npm

    cd backend
    npm install
}

package() {
    install -d "$pkgdir"/opt/lib/zshelf

    cp -r "$srcdir"/backend "$pkgdir"/opt/lib/zshelf/backend
    cp "$srcdir"/config.json "$pkgdir"/opt/lib/zshelf
    install -D -m 755 -t "$pkgdir"/opt/lib/zshelf "$srcdir"/zshelf

    install -d "$pkgdir"/opt/bin
    ln -s /opt/lib/zshelf/zshelf "$pkgdir"/opt/bin/zshelf
    install -d "$pkgdir"/opt/etc/zshelf
    ln -s /opt/lib/zshelf/config.json "$pkgdir"/opt/bin/zshelf

    install -D -m 644 -t "$pkgdir"/opt/etc/draft "$srcdir"/zshelf.draft
    install -D -m 644 -t "$pkgdir"/opt/etc/draft/icons "$srcdir"/zshelf.png
}

configure() {
    echo ""
    echo "To download books, you have to configure domain and cookie first."
    echo "Please follow instructions on:"
    echo "https://github.com/khanhas/zshelf#important-configure-domain-and-cookie"
    echo "Config file locates at:" /opt/share/zshelf/config.json
    echo ""
}
