#!/usr/bin/env bash
# Copyright (c) 2020 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(rm2fb)
timestamp=2020-10-10T01:41+00:00
maintainer="raisjn <of.raisjn@gmail.com>"
license=MIT
pkgdesc="Interface to the reMarkable 2 framebuffer"
url="https://github.com/ddvk/remarkable2-framebuffer"
pkgver=1.0.0-6
section="devel"

image=qt:v1.1
source=(
    https://github.com/ddvk/remarkable2-framebuffer/archive/cd2766864c7985fa50cdf85f4ae0a411d7ca4e56.zip
    rm2fb.conf
    rm2fb.service
    rm2fb-server
    rm2fb-client
)
sha256sums=(
    c274c458270eec28950834bd28ff069a0af65e40fcc288a8ff28235001e8914f
    SKIP
    SKIP
    SKIP
    SKIP
)

build() {
    qmake
    make
}

package() {
    mkdir -p "$pkgdir"/opt/lib "$pkgdir"/opt/etc "$pkgdir"/opt/bin
    install -D -m 755 "$srcdir"/src/client/librm2fb_client.so.${pkgver%-*} "$pkgdir"/opt/lib/
    install -D -m 755 "$srcdir"/src/server/librm2fb_server.so.${pkgver%-*} "$pkgdir"/opt/lib/
    install -D -m 755 "$srcdir"/rm2fb-server "$pkgdir"/opt/bin/
    install -D -m 755 "$srcdir"/rm2fb-client "$pkgdir"/opt/bin/
    install -D -m 644 "$srcdir"/rm2fb.conf "$pkgdir"/etc/systemd/system.conf.d/01-rm2fb.conf
    install -D -m 644 "$srcdir"/rm2fb.service "$pkgdir"/lib/systemd/system/rm2fb.service
}

configure() {
    systemctl daemon-reload
    systemctl enable rm2fb --now
    # Restart xochitl if it's running
    if systemctl --quiet is-active xochitl; then
        # Reset the crash count so we don't trigger remarkable-fail
        echo "0" > /tmp/crashnum
        systemctl restart xochitl
    fi
}

preremove() {
    if systemctl list-units --full -all | grep -Fq 'rm2fb.service'; then
        systemctl disable rm2fb --now
    fi
    echo -n "make sure "
    if ! is-enabled xochitl.service; then
        echo "to re-enable xochitl with 'systemctl enable xochitl --now'"
        echo -n "and "
    fi
    echo "to disable / uninstall any launchers like draft, oxide or remux before"
    echo "rebooting your tablet to complete the uninstallation"
}
