#!/usr/bin/env bash

source "${BASH_SOURCE%/*}"/lib
usage="$0 PACKAGESDIR WORKDIR

Build all packages described in PACKAGESDIR.
The WORKDIR must be a non-existent directory in which the build is performed.

Arguments:

    -h, --help      Show this help message."

if [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; then
    echo "$usage"
    exit
fi

if [[ $# -lt 2 ]]; then
    error "Missing arguments. Use the --help flag for more information."
fi

pkgsdir="$1"
workdir="$2"

[[ -d $workdir ]] && files="$(ls -qA -- "$workdir")" && [[ -n $files ]] \
    && error "Working directory exists and is not empty"
mkdir -p "$workdir"

pkgsworkdir="$workdir"/package
mkdir "$pkgsworkdir"

repodir="$workdir"/repo
mkdir "$repodir"

# Build each individual package
for pkgpath in "$pkgsdir"/*
do
    pkgname="$(basename "$pkgpath")"
    pkgworkdir="$pkgsworkdir"/"$pkgname"
    status "Building $pkgname in $pkgworkdir"

    "${BASH_SOURCE%/*}"/build-package "$pkgpath" "$pkgworkdir"
    mv "$pkgworkdir"/*.ipk "$repodir"
done

# Build packages index
opkg-make-index --checksum sha256 -p "$repodir"/Packages "$repodir"

# Set atime and mtime to fixed timestamp for all files
find "$repodir" -exec touch --no-dereference --date="@${SOURCE_DATE_EPOCH}" {} +
status "Done. Result is in $repodir"
