#!/usr/bin/env bash

set -e
source "${BASH_SOURCE%/*}"/lib

usage="$0 [OPTION]... RECIPEDIR WORKDIR

Build a package following the recipe defined in RECIPEDIR.
The WORKDIR must be a non-existent directory in which the build is performed.

Arguments:

    -h              Show this help message."

helpflag=

while getopts h name; do
    case $name in
        h) helpflag=1 ;;
        *) error "Invalid option. Use the -h flag for more information." ;;
    esac
done

shift $((OPTIND - 1))

if [[ -n $helpflag ]]; then
    echo "$usage"
    exit
fi

if [[ $# -eq 0 ]]; then
    error "Missing RECIPEDIR and WORKDIR arguments. Use the -h flag for more information."
fi

if [[ $# -eq 1 ]]; then
    error "Missing WORKDIR argument. Use the -h flag for more information."
fi

if [[ $# -gt 2 ]]; then
    error "Extraneous arguments. Use the -h flag for more information."
fi

recipedir="$1"
workdir="$2"

# Create working directories
[[ -d $workdir ]] && files="$(ls -qA -- "$workdir")" && [[ -n $files ]] \
    && error "Working directory '$workdir' exists and is not empty"
mkdir -p "$workdir"

srcdir="$workdir"/src
mkdir "$srcdir"

pkgdir="$workdir"/pkg
mkdir "$pkgdir"

ctldir="$workdir"/control
mkdir "$ctldir"

ardir="$workdir"/ar
mkdir "$ardir"

# Define the SOURCE_DATE_EPOCH to the date of latest commit
# See <https://reproducible-builds.org/docs/source-date-epoch/>
SOURCE_DATE_EPOCH="$(git log -1 --pretty=%ct)"
export SOURCE_DATE_EPOCH

# Load package info and script
load-recipe "$recipedir"

# Fetch source files
status "Fetching source files"
git clone --quiet --recursive "$origin" "$srcdir"
pushd "$srcdir" > /dev/null
git checkout --quiet "$revision"
popd > /dev/null

# Set atime and mtime to fixed timestamp for all source files
find "$srcdir" -exec touch --no-dereference --date="@${SOURCE_DATE_EPOCH}" {} +

# Run build script inside a Docker container
status "Building package"

docker container run --interactive --rm \
    --mount type=bind,src="$(realpath "$recipedir")",dst=/recipe \
    --mount type=bind,src="$(realpath "$srcdir")",dst=/src \
    "$(image-name "$image")" /bin/bash \
<<CMDS
    source /recipe/package
    cd /src
    build
CMDS

# Run packaging script
package

# Create control file and archive
ctlfile="$ctldir"/control

{
    echo "Package: $pkgname"
    echo "Version: $pkgver"
    echo "License: $license"
    echo "Section: $section"
    echo "Maintainer: $maintainer"
    echo "Architecture: $arch"
    echo "Description: $pkgdesc"
    [[ -n $depends ]] && echo "Depends: $depends"
    [[ -n $conflicts ]] && echo "Conflicts: $conflicts"
} >> "$ctlfile"

# Copy install scripts
[[ -f "$recipedir"/preinst ]] && install -D -m 755 "$recipedir"/preinst "$ctldir"/preinst
[[ -f "$recipedir"/postinst ]] && install -D -m 755 "$recipedir"/postinst "$ctldir"/postinst
[[ -f "$recipedir"/prerm ]] && install -D -m 755 "$recipedir"/prerm "$ctldir"/prerm
[[ -f "$recipedir"/postrm ]] && install -D -m 755 "$recipedir"/postrm "$ctldir"/postrm

# Create archives
status "Creating archive"
pkgar="$ardir"/data.tar.gz
ctlar="$ardir"/control.tar.gz
versionar="$ardir"/debian-binary
arar="$workdir/$(archive-name "$recipedir")"

echo "2.0" >> "$versionar"
rtar -zcf "$pkgar" -C "$pkgdir" .
rtar -zcf "$ctlar" -C "$ctldir" .
rtar -zcf "$arar" -C "$ardir" .

status "Done. Result is in $arar"
