#!/usr/bin/env bash

set -e
source "${BASH_SOURCE%/*}"/lib

usage="$0 [OPTION]... REPODIR [REMOTEREPO]

Compare a local repository to an online published version.
If REMOTEREPO is omitted 'https://toltec.delab.re/CURRENT-CHANNEL' is used.

Options:

    -h              Show this help message."

helpflag=

while getopts hf name; do
    case $name in
        h) helpflag=1 ;;
        *) error "Invalid option. Use the -h flag for more information." ;;
    esac
done

shift $((OPTIND - 1))

if [[ -n $helpflag ]]; then
    echo "$usage"
    exit
fi

if [[ $# -eq 0 ]]; then
    error "Missing REPODIR argument. Use the -h flag for more information."
fi

repodir="$1"
remoterepo="https://toltec.delab.re/$(channel)"

if [[ $# -eq 2 ]]; then
    remoterepo="$2"
fi

if [[ $# -gt 2 ]]; then
    error "Extraneous arguments. Use the -h flag for more information."
fi

differs=

for repofile in "$repodir"/*; do
    file="$(realpath --relative-to="$repodir" "$repofile")"
    remotefile="$remoterepo"/"$file"

    status "Comparing $file"

    if ! rcurl "$remotefile" -o - | diff - "$repofile" > /dev/null; then
        echo "! $file differs between the local and the remote repositories."
        differs=yes
    fi
done

if [[ -n $differs ]]; then
    error "Some files differ"
else
    status "Done"
fi
