#!/usr/bin/env bash

source "${BASH_SOURCE%/*}"/lib
usage="$0 WORKDIR

Upload all packages in the WORKDIR directory to a remote server.

Environment variables:

    REMOTE_PATH         Fully qualified path of a remote server
    SSH_PRIVATE_KEY     Private SSH key used for authenticating to the server
    SSH_KNOWN_HOSTS     Valid public keys of the server

Arguments:

    -h, --help      Show this help message."

if [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; then
    echo "$usage"
    exit
fi

if [[ $# -lt 1 ]]; then
    error "Missing arguments. Use the --help flag for more information."
fi

pkgsdir="$1"

[[ -z $REMOTE_PATH ]] && error "Missing or empty REMOTE_PATH env var"
[[ -z $SSH_PRIVATE_KEY ]] && error "Missing or empty SSH_PRIVATE_KEY env var"
[[ -z $SSH_KNOWN_HOSTS ]] && error "Missing or empty SSH_KNOWN_HOSTS env var"

# Configure SSH access to the remote server
mkdir -p $HOME/.ssh
chmod 700 $HOME/.ssh
echo "$SSH_PRIVATE_KEY" > $HOME/.ssh/id_rsa
echo "$SSH_KNOWN_HOSTS" >> $HOME/.ssh/known_hosts
chmod 600 $HOME/.ssh/*

# Upload results
status "Uploading repository to remote"
rsync -avz --delete \
    -e "ssh -i \"$HOME\"/.ssh/id_rsa -o UserKnownHostsFile=\"$HOME\"/.ssh/known_hosts" \
    "$pkgsdir/" "$REMOTE_PATH"
