#!/usr/bin/env bash

set -e
source scripts/package-lib

usage="$0 [OPTION]... RECIPESDIR WORKDIR REPODIR [REMOTEREPO]

Build new or updated packages defined in RECIPESDIR and create a package index.
Packages are built in subdirectories of WORKDIR and resulting artifacts are
gathered in REPODIR.  If REMOTEREPO is omitted,
'https://toltec.delab.re/testing' is used.

Options:

    -h              Show this help message.
    -l              Only build packages locally, do not reuse existing packages
                    from the publishing server."

helpflag=
localflag=

while getopts hl name; do
    case $name in
        h) helpflag=1 ;;
        l) localflag=1 ;;
        *) error "Invalid option. Use the -h flag for more information." ;;
    esac
done

shift $((OPTIND - 1))

if [[ -n $helpflag ]]; then
    echo "$usage"
    exit
fi

if [[ $# -eq 0 ]]; then
    error "Missing RECIPESDIR, WORKDIR and REPODIR arguments. Use the -h flag for more information."
fi

if [[ $# -eq 1 ]]; then
    error "Missing WORKDIR and REPODIR arguments. Use the -h flag for more information."
fi

if [[ $# -eq 2 ]]; then
    error "Missing REPODIR argument. Use the -h flag for more information."
fi

remoterepo="https://toltec.delab.re/testing"

if [[ $# -eq 4 ]]; then
    remoterepo="$4"
fi

if [[ $# -gt 4 ]]; then
    error "Extraneous arguments. Use the -h flag for more information."
fi

recipesdir="$1"

workdir="$2"
mkdir -p "$workdir"

repodir="$3"
mkdir -p "$repodir"

# Build missing packages or get them from the remote server
# Each recipe is loaded in a subshell to avoid leaking metadata fields
for recipedir in "$recipesdir"/*; do
    (
        load-recipe "$recipedir"
        pkgid="$(package-id)"

        if [[ ! -f "$repodir"/"$pkgid.ipk" ]]; then
            if [[ -n $localflag ]] || ! rsecurl --remote-time "$remoterepo"/"$pkgid.ipk" -o "$repodir"/"$pkgid.ipk"; then
                section "Building $pkgid"
                scripts/package-build "$recipedir" "$workdir"
                cp "$workdir"/"$pkgid"/"$pkgid".ipk "$repodir"
            else
                section "Reusing $pkgid from $remoterepo"
            fi
        fi
    )
done

# Build packages index
section "Making packages index"
"${BASH_SOURCE%/*}"/opkg/opkg-make-index --checksum sha256 -p "$repodir"/Packages "$repodir"

# Set atime and mtime to the date of latest commit for the packages index
lastcommitdate="$(git log -1 --pretty=%ct)"
touch --no-dereference --date="@$lastcommitdate" \
    "$repodir"/Packages \
    "$repodir"/Packages.gz \
    "$repodir"/Packages.stamps


section "Making packages web listing"
scripts/repo-build-web "$recipesdir" "$repodir"

section "Done. Result is in $repodir"
