#!/usr/bin/bash
# Copyright (c) 2021 The Toltec Contributors
# SPDX-License-Identifier: MIT

set -e
source scripts/package-lib

usage="$0 SRCDIR OUTDIR

Generate the Toltec website from SRCDIR in OUTDIR."

helpflag=

while getopts h name; do
    case $name in
        h) helpflag=1 ;;
        *) error "Invalid option. Use the -h flag for more information." ;;
    esac
done

shift $((OPTIND - 1))

if [[ -n $helpflag ]]; then
    echo "$usage"
    exit
fi

if [[ $# -eq 0 ]]; then
    error "Missing SRCDIR and OUTDIR arguments. Use the -h flag for more information."
fi

if [[ $# -eq 1 ]]; then
    error "Missing OUTDIR argument. Use the -h flag for more information."
fi

if [[ $# -gt 2 ]]; then
    error "Extraneous arguments. Use the -h flag for more information."
fi

srcdir="$1"
outdir="$2"

[[ -d $2 ]] && files="$(ls -qA -- "$2")" && [[ -n $files ]] \
    && error "Output directory '$2' exists and is not empty"

mkdir -p "$outdir"

# Copy bootstrap script
cp scripts/bootstrap/bootstrap "$outdir"
bootstrap_checksum="$(sha256sum scripts/bootstrap/bootstrap | cut -b-64)"

# Compile reStructuredText sources
cp -r "$srcdir"/* "$outdir"
pushd "$outdir" > /dev/null

cat > defs.rst << RST
.. |bootstrap-hash| replace:: $bootstrap_checksum
RST

rst2html5 index.rst > index.html
rm index.rst docutils.conf defs.rst
popd > /dev/null
