#!/usr/bin/env bash
# Copyright (c) 2023 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(hstr)
pkgdesc="Shell command history suggest box"
url=https://github.com/dvorka/hstr
pkgver=3.1-1
timestamp=2023-04-18T10:48Z
section="utils"
maintainer="gbyl <gbyl@users.noreply.github.com>"
license=Apache-2.0

image=base:v3.1
source=("https://github.com/dvorka/hstr/archive/refs/tags/${pkgver%-*}.zip")
sha256sums=(12f83d1c2a2216854b9389053022591e96c2f11d1e6ec0fae0355b7e43a76ac1)

build() {
    ./configure && make && make install
}

package() {
    install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/hstr
}
