#!/usr/bin/env bash
# Copyright (c) 2025 The Toltec Contributors
# SPDX-License-Identifier: MIT
arch=(
    rmallos2
    rmallos3
    rm1os3v22
    rm2os3v22
    rmppos3v22
    rmppmos3v22
)
pkgnames=(display)
pkgdesc="Metapackage for allowing applications to display to the screen"
timestamp=2024-05-24T06:12:38Z
maintainer="Eeems <eeems@eeems.email>"
license=MIT
url="https://toltec-dev.org"
pkgver=2:0.0.1-1
section="devel"
installdepends=()
installdepends_rmallos2=(rm2fb-server rm2fb-client)
installdepends_rmallos3=(rm2fb-server rm2fb-client)
installdepends_rm1os3v22=(rm2fb-server rm2fb-client)
installdepends_rm2os3v22=(rm2fb-server rm2fb-client)

package() {
    true
}
