#!/usr/bin/env bash
# Copyright (c) 2021 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(doomarkable)
pkgdesc="DOOM game"
url=https://github.com/LinusCDE/doomarkable
pkgver=0.4.0-1
timestamp=2021-10-25T23:02Z
section="games"
maintainer="Linus K. <linus@cosmos-ink.net>"
license=MIT
installdepends=(display)
flags=(patch_rm2fb)

image=rust:v2.2
source=(https://github.com/LinusCDE/doomarkable/archive/0.4.0.zip)
sha256sums=(39988c0a607560787789b0e71aa34059c64d11ba1b98e11145d08677ed420c5f)

build() {
    # Fall back to system-wide config
    rm .cargo/config
    cargo build --release
}

package() {
    install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/target/armv7-unknown-linux-gnueabihf/release/doomarkable
    install -D -m 644 -t "$pkgdir"/opt/etc/draft "$srcdir"/doomarkable.draft
    install -D -m 644 -t "$pkgdir"/opt/etc/draft/icons "$srcdir"/doomarkable.png
}
