#!/usr/bin/env bash
# Copyright (c) 2021 The Toltec Contributors
# SPDX-License-Identifier: MIT

archs=(rm1 rm2)
pkgnames=(doomarkable)
pkgdesc="DOOM game"
url=https://github.com/LinusCDE/doomarkable
pkgver=0.4.1-4
timestamp=2021-10-31T16:15Z
section="games"
maintainer="Linus K. <linus@cosmos-ink.net>"
license=MIT
installdepends=(display)
flags=(patch_rm2fb)

image=rust:v3.1
source=(https://github.com/LinusCDE/doomarkable/archive/7d10769d625fbe733768e39cf5006cde341d2fef.zip)
sha256sums=(df86cc87d2dde7993f47f809faaab8568abe4dd2987e5ab4e00e337caef03706)

build() {
    # Fall back to system-wide config
    rm .cargo/config
    cargo build --release
}

package() {
    install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/target/armv7-unknown-linux-gnueabihf/release/doomarkable
    install -D -m 644 -t "$pkgdir"/opt/etc/draft "$srcdir"/doomarkable.draft
    install -D -m 644 -t "$pkgdir"/opt/etc/draft/icons "$srcdir"/doomarkable.png
}
