#!/usr/bin/env bash
# Copyright (c) 2020 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(rempack)
pkgdesc="A user friendly package manager frontend for opkg"
archs=(rmall)
url="https://github.com/rexxar-tc/rempack"
pkgver=1.1.3
timestamp=2025-03-01T04:26:09-05:00
section=admin
maintainer="Brant Martin <toltec@brantmartin.com>"
license=MIT
image=base:v3.1
installdepends=(display)
source=(
    http://gitlab.onionstorm.net/rolenthedeep/rempack/-/archive/1.1.3/rempack-1.1.3.zip
    rempack.draft
    rempack.oxide
)
sha256sums=(
    2a82d3d8f9db9d0d8a784c8560c582f5e7513e293be1c07fdd86352f3d3b3edc
    SKIP
    SKIP
)
build() {
    cd $srcdir
    mkdir output
    cmake -S . -B output --preset "Release Native"
    cmake --build output --target rempack
}

package() {
    install -D -m 755 "$srcdir"/output/rempack "$pkgdir"/opt/bin/rempack
    install -D -m 644 "$srcdir"/rempack.draft "$pkgdir"/opt/etc/draft/rempack.draft
    install -D -m 644 "$srcdir"/rempack.oxide "$pkgdir"/opt/usr/share/applications/rempack.oxide
}
