#!/usr/bin/env bash
# Copyright (c) 2021 The Toltec Contributors
# SPDX-License-Identifier: MIT

archs=(rm1 rm2)
pkgnames=(toltec-base)
pkgdesc="Metapackage defining the base set of packages in a Toltec install"
url=https://toltec-dev.org/
pkgver=1.1-1
timestamp=2022-11-07T20:19:57Z
section="utils"
maintainer="Eeems <eeems@eeems.email>"
license=MIT
installdepends=(toltec-bootstrap toltec-completion)
installdepends_rm1=(open-remarkable-shutdown)
installdepends_rm2=(rm2-suspend-fix)

source=()
sha256sums=()

package() {
    touch "$srcdir"/emptyfile
    install -D -m 666 -t "$pkgdir"/usr/share/toltec/reenable.d/toltec-base "$srcdir"/emptyfile
}

configure() {
    if is-enabled "update-engine.service"; then
        echo "Disabling automatic update"
        systemctl disable --now update-engine
    fi
    echo "Disabling usb1 network device to avoid long boots"
    systemctl mask sys-subsystem-net-devices-usb1.device
}
