#!/usr/bin/env bash
# Copyright (c) 2021 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(erode fret oxide rot tarnish decay corrupt anxiety)
pkgver=2.2.2-1
timestamp=2021-07-18T16:43:24Z
maintainer="Eeems <eeems@eeems.email>"
license=MIT
flags=(patch_rm2fb)

image=qt:v2.1
_srcver="v${pkgver%-*}"
source=("https://github.com/Eeems/oxide/archive/refs/tags/$_srcver.tar.gz")
sha256sums=(0d221c084f5583075052dd2369144c04cf97010d5641ebc029ae596d8ef1a40d)

build() {
    find . -name "*.pro" -type f -print0 \
        | xargs -r -0 sed -i 's/linux-oe-g++/linux-arm-remarkable-g++/g'
    make release
}

erode() {
    pkgdesc="Task manager"
    url=https://github.com/Eeems/oxide/tree/master/applications/process-manager
    section="admin"
    installdepends=(display "tarnish=$pkgver")

    package() {
        install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/release/opt/bin/erode
        install -D -m 644 -t "$pkgdir"/opt/etc/draft/icons "$srcdir"/release/opt/etc/draft/icons/erode.svg
        install -D -m 644 -t "$pkgdir"/opt/etc/draft/icons "$srcdir"/release/opt/etc/draft/icons/erode-splash.png
        install -D -m 644 -t "$pkgdir"/opt/usr/share/applications "$srcdir"/release/opt/usr/share/applications/codes.eeems.erode.oxide
    }
}

fret() {
    pkgdesc="Take screenshots"
    url=https://github.com/Eeems/oxide/tree/master/applications/screenshot-tool
    section="utils"
    installdepends=("tarnish=$pkgver")

    package() {
        install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/release/opt/bin/fret
        install -D -m 644 -t "$pkgdir"/opt/usr/share/applications "$srcdir"/release/opt/usr/share/applications/codes.eeems.fret.oxide
    }
}

oxide() {
    pkgdesc="Launcher application"
    url=https://github.com/Eeems/oxide/tree/master/applications/launcher
    section="launchers"
    installdepends=(display "erode=$pkgver" "fret=$pkgver" "tarnish=$pkgver" "rot=$pkgver" "decay=$pkgver")

    package() {
        install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/release/opt/bin/oxide
        install -D -m 644 -t "$pkgdir"/opt/etc "$srcdir"/release/opt/etc/oxide.conf
        install -D -m 644 -t "$pkgdir"/opt/etc/draft/icons "$srcdir"/release/opt/etc/draft/icons/oxide-splash.png
        install -D -m 644 -t "$pkgdir"/opt/usr/share/applications "$srcdir"/release/opt/usr/share/applications/codes.eeems.oxide.oxide
    }
    configure() {
        if ! is-enabled "tarnish.service"; then
            echo ""
            echo "Run the following command(s) to use $pkgname as your launcher"
            how-to-enable "tarnish.service"
            echo ""
        fi
    }
}

rot() {
    pkgdesc="Manage Oxide settings through the command line"
    url=https://github.com/Eeems/oxide/tree/master/applications/settings-manager
    section="admin"
    installdepends=("tarnish=$pkgver")

    package() {
        install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/release/opt/bin/rot
    }
}

tarnish() {
    pkgdesc="Service managing power states, connectivity and buttons"
    url=https://github.com/Eeems/oxide/tree/master/applications/system-service
    section="devel"
    installdepends=(display xochitl)

    package() {
        install -D -m 644 -t "$pkgdir"/etc/dbus-1/system.d "$srcdir"/release/etc/dbus-1/system.d/codes.eeems.oxide.conf
        install -D -m 644 -t "$pkgdir"/lib/systemd/system "$srcdir"/release/etc/systemd/system/tarnish.service
        install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/release/opt/bin/tarnish
    }
    configure() {
        systemctl daemon-reload
    }
    preremove() {
        if is-active tarnish; then
            echo "Stopping tarnish"
            systemctl stop tarnish
        fi
        if is-enabled tarnish; then
            echo "Disabling tarnish"
            systemctl disable tarnish
        fi
    }
    postremove() {
        systemctl daemon-reload
    }
}

decay() {
    pkgdesc="Lockscreen application"
    url=https://github.com/Eeems/oxide/tree/master/applications/lockscreen
    section="utils"
    installdepends=(display "tarnish=$pkgver")

    package() {
        install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/release/opt/bin/decay
        install -D -m 644 -t "$pkgdir"/opt/usr/share/applications "$srcdir"/release/opt/usr/share/applications/codes.eeems.decay.oxide
    }
}
corrupt() {
    pkgdesc="Task Switcher for Oxide"
    url=https://github.com/Eeems/oxide/tree/master/applications/task-switcher
    section="utils"
    installdepends=(display "tarnish=$pkgver")

    package() {
        install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/release/opt/bin/corrupt
        install -D -m 644 -t "$pkgdir"/opt/usr/share/applications "$srcdir"/release/opt/usr/share/applications/codes.eeems.corrupt.oxide
    }
}

anxiety() {
    pkgdesc="Screenshot viewer for Oxide"
    url=https://github.com/Eeems/oxide/tree/master/applications/screenshot-viewer
    section="utils"
    installdepends=(display "tarnish=$pkgver")

    package() {
        install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/release/opt/bin/anxiety
        install -D -m 644 -t "$pkgdir"/opt/usr/share/applications "$srcdir"/release/opt/usr/share/applications/codes.eeems.anxiety.oxide
        install -D -m 644 -t "$pkgdir"/opt/etc/draft/icons "$srcdir"/release/opt/etc/draft/icons/image.svg
        install -D -m 644 -t "$pkgdir"/opt/etc/draft/icons "$srcdir"/release/opt/etc/draft/icons/anxiety-splash.png
    }
}
