#!/usr/bin/env bash
# Copyright (c) 2020 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(restream)
pkgdesc="Binary framebuffer capture tool for the reStream script"
url=https://github.com/rien/reStream
pkgver=1.0.0-1
timestamp=2021-01-05T19:08:03Z
section="screensharing"
maintainer="Dan Shick <dan.shick@gmail.com>"
license=MIT
conflicts=(rm2fb)
image=rust:v1.3
source=(https://github.com/rien/reStream/archive/1.0.tar.gz)
sha256sums=(07457895927c9dd3d9566d6d432dbd0b76f97dfff45dc2964adfcc3091a2ce0f)

build() {
    # Fall back to system-wide config
    rm .cargo/config

    cargo build --release --bin restream
}

package() {
    install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/target/armv7-unknown-linux-gnueabihf/release/restream
}

configure() {
    cat << 'MSG'

This app is only the device-side half of reStream. The companion script for
consuming the output of this app can be found at
<https://github.com/rien/reStream>.

The script may need to be adjusted to target '/opt/bin/restream' instead of
'$HOME/restream', or you can create a symlink on your device with:

    ln -s /opt/bin/restream $HOME/restream

MSG
}
