#!/usr/bin/env bash
# Copyright (c) 2023 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(libglib)
pkgdesc="Low-level core library that forms the basis for projects such as GTK+ and GNOME."
url=https://gitlab.gnome.org/GNOME/glib/
timestamp=2023-12-06T21:45:00Z
section=util
maintainer="Eeems <eeems@eeems.email>"
license=GPL-2.0-or-later
_glib_ver=2.78.3
pkgver=${_glib_ver}-1
source=("https://download.gnome.org/sources/glib/2.78/glib-${_glib_ver}.tar.xz")
sha256sums=(609801dd373796e515972bf95fc0b2daa44545481ee2f465c4f204d224b2bc21)
image=base:v3.1
makedepends=(build:git)
provides=(
    gapplication
    gdbus
    gio
    glib
    gsettings
    gtester
    libgio
    libgthread
    pcre2grep
)

build() {
    meson setup \
        --cross-file /usr/share/meson/cross/arm-linux-gnueabihf \
        --prefix /opt/usr/lib/libglib \
        "${srcdir}/builddir"
    meson compile -C "${srcdir}/builddir"
    DESTDIR="${srcdir}/installdir" meson install -C "${srcdir}/builddir"
}

package() {
    cp -al "${srcdir}/installdir/." "${pkgdir}"
}
