#!/usr/bin/env bash
# Copyright (c) 2021 The Toltec Contributors
# SPDX-License-Identifier: MIT

archs=(rm1 rm2)
pkgnames=(retris)
pkgdesc="Tetris game"
url=https://github.com/LinusCDE/retris
pkgver=0.6.4-2
timestamp=2021-01-30T02:41Z
section="games"
maintainer="Linus K. <linus@cosmos-ink.net>"
license=MIT
installdepends=(display)
flags=(patch_rm2fb)

image=rust:v3.3
source=(https://github.com/LinusCDE/retris/archive/0.6.4-1.zip)
sha256sums=(934fa07c962f5b35d4e0c4d40631aa954c72a9d147b40a6bb49c5d3dc0a3684e)

build() {
    cargo build --release
}

package() {
    install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/target/armv7-unknown-linux-gnueabihf/release/retris
    install -D -m 644 "$srcdir"/oxide "$pkgdir"/opt/etc/draft/retris
    install -D -m 644 "$srcdir"/icon.png "$pkgdir"/opt/etc/draft/icons/retris.png
}
