#!/usr/bin/env bash
# Copyright (c) 2024 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(ripgrep)
pkgdesc="Modern grep for recursive regex pattern searching"
url=https://github.com/BurntSushi/ripgrep
pkgver=14.1.0-1
timestamp=2024-01-06T18:41Z
section="utils"
maintainer="gbyl <gbyl@users.noreply.github.com>"
license=MIT
installdepends=(libpcre2)

image=rust:v3.1
source=("https://github.com/BurntSushi/ripgrep/archive/refs/tags/${pkgver%-*}.zip")
sha256sums=(821cb40ecddb6d539f6d8ea2490acc6b5e2a45723f884f5e14a0c115d1523b4d)

build() {
    cargo install --features 'pcre2'
}

package() {
    install -D -m 755 "$srcdir"/target/armv7-unknown-linux-gnueabihf/release/rg "$pkgdir"/opt/bin/rg
}
