#!/usr/bin/env bash
# Copyright (c) 2023 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(ripgrep)
pkgdesc="Modern grep for recursive regex pattern searching"
url=https://github.com/BurntSushi/ripgrep
pkgver=14.0.3-1
timestamp=2023-11-28T21:22Z
section="utils"
maintainer="gbyl <gbyl@users.noreply.github.com>"
license=MIT

image=rust:v2.3
source=("https://github.com/BurntSushi/ripgrep/archive/refs/tags/14.0.3.zip")
sha256sums=(eb91f202fc25d51755390736775a7e7f8e146eb97e584aaa01fb0c45aa5de654)

build() {
    cargo build --release
}

package() {
    install -D -m 755 "$srcdir"/target/armv7-unknown-linux-gnueabihf/release/rg "$pkgdir"/opt/bin/rg
}
