#!/usr/bin/env bash
# Copyright (c) 2021 The Toltec Contributors
# SPDX-License-Identifier: MIT

archs=(rmall)
pkgnames=(mmc-utils)
pkgdesc="A tool for monitoring the eMMC protocol"
url=https://git.kernel.org/pub/scm/utils/mmc/mmc-utils.git/
pkgver=1.0-0
timestamp=2021-08-12T19:41:07Z
section="devel"
maintainer="Alistair Francis <alistair@alistair23.me>"
license=GPL-2.0-only

image=base:v2.2
source=(
    "https://git.kernel.org/pub/scm/utils/mmc/mmc-utils.git/snapshot/mmc-utils-7769a4d7abe339ce273c13a203394a79a11fcff9.tar.gz"
    0001-Makefile-Remove-Werror.patch
)
sha256sums=(
    0578e546d8893b6207180def7966e7314cae54c237a931b8f94779ce5c7d0668
    SKIP
)

build() {
    # Use our toolchain
    export AR=arm-linux-gnueabihf-ar
    export CC=arm-linux-gnueabihf-gcc
    export STRIP=arm-linux-gnueabihf-strip

    patch < "$srcdir"/0001-Makefile-Remove-Werror.patch
    make -j4
}

package() {
    DESTDIR="$pkgdir" make -C "$srcdir" install
}
