#!/usr/bin/env bash
# Copyright (c) 2021 The Toltec Contributors
# SPDX-License-Identifier: MIT

archs=(rm1 rm2 rmpp rmppm)
pkgnames=(mmc-utils mmc-utils-doc)
pkgdesc="A tool for monitoring the eMMC protocol"
url=https://git.kernel.org/pub/scm/utils/mmc/mmc-utils.git/
pkgver=1.0-3
timestamp=2021-08-12T19:41:07Z
section="utils"
maintainer="Alistair Francis <alistair@alistair23.me>"
license=GPL-2.0-only

image=base:v3.2
image_rmpp=base:v4.0
image_rmppm=base:v4.0
preparedepends=(build:git)
source=(
    0001-Makefile-Remove-Werror.patch
)
sha256sums=(
    SKIP
)
_commit=7769a4d7abe339ce273c13a203394a79a11fcff9

prepare() {
    cd "$srcdir"
    mkdir mmc-utils
    cd mmc-utils
    git init
    git fetch --depth=1 "https://git.kernel.org/pub/scm/utils/mmc/mmc-utils.git" "$_commit"
    git checkout -f "$_commit"
    patch < "$srcdir"/0001-Makefile-Remove-Werror.patch
}

build() {
    # Use our toolchain
    export AR="${CROSS_COMPILE}ar"
    export CC="${CROSS_COMPILE}gcc"
    export STRIP="${CROSS_COMPILE}strip"

    cd "$srcdir"/mmc-utils
    make -j4
}

mmc-utils() {
    package() {
        install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/mmc-utils/mmc
    }
}

mmc-utils-doc() {
    installdepends=(man-db)
    pkgdesc="Man files for mmc-utils"
    package() {
        install -D -m 644 <(gzip -c "$srcdir"/mmc-utils/man/mmc.1) "$pkgdir"/opt/share/man/man1/mmc1.gz
    }
}
