name: pr-labels
on:
    pull_request:
        types: [opened, reopened, synchronize, edited, labeled, unlabeled]
jobs:
    check-labels:
        name: Check that PRs against the stable branch are labelled correctly
        runs-on: ubuntu-22.04
        steps:
            - name: Check labels
              run: |
                [[ '${{ github.base_ref }}' != stable ]] \
                || [[ '${{ contains(github.event.pull_request.labels.*.name, 'merge') }}' == true ]]
