name: stable
on:
  push:
    branches:
      - stable
jobs:
  dependencies:
    name: Generate dependency chains
    runs-on: ubuntu-24.04
    outputs:
      recipes-matrix: ${{ steps.recipes-matrix.outputs.JSON_CONTENT }}
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v4
      - name: Setup Toltec dependencies
        uses: ./.github/actions/setup
      - name: Cache repo
        uses: actions/cache@v4
        with:
          path: build/repo
          key: stable-${{ hashFiles('package/*/package') }}
      - name: Get recipe lists
        id: recipes-matrix
        run: |
          make .venv/bin/activate
          echo 'JSON_CONTENT<<EOF' >> $GITHUB_OUTPUT
          echo '{"include":' >> $GITHUB_OUTPUT
          make dependency-chain >> $GITHUB_OUTPUT
          echo "}" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
        env:
          FLAGS: --remote-repo ${{ secrets.REMOTE_HTTP }}/stable
  build:
    name: Build ${{ matrix.recipes }}
    runs-on: ubuntu-24.04
    needs: [dependencies]
    strategy:
      matrix: ${{ fromJson(needs.dependencies.outputs.recipes-matrix) }}
      fail-fast: false
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v4
      - name: Setup Toltec dependencies
        uses: ./.github/actions/setup
      - name: Cache repo
        uses: actions/cache@v4
        with:
          path: build/repo
          key: stable-${{ hashFiles('package/*/package') }}
      - name: Build packages
        run: make repo-new
        env:
          FLAGS: --remote-repo ${{ secrets.REMOTE_HTTP }}/stable --filter "${{ matrix.recipes }}"
          CLEANUP: 1
      - name: Upload all ipk
        uses: actions/upload-artifact@v4
        with:
          name: recipes-${{ matrix.recipes }}
          path: build/repo/**/*.ipk
  deploy:
    name: Deploy stable branch
    runs-on: ubuntu-24.04
    needs: [build]
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v4
      - name: Setup Toltec dependencies
        uses: ./.github/actions/setup
      - name: Cache repo
        uses: actions/cache@v4
        with:
          path: build/repo
          key: stable-${{ hashFiles('package/*/package') }}
      - name: Download all packages
        uses: actions/download-artifact@v5
        with:
          path: build/repo
          pattern: recipes-*
          merge-multiple: true
      - name: Build packages for stable
        run: make repo
        env:
          FLAGS: --remote-repo ${{ secrets.REMOTE_HTTP }}//stable
          CLEANUP: 1
      - name: Sync packages with the remote repository
        uses: ./.github/actions/sync-repository
        with:
          local-path: build/repo/
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          ssh-port: ${{ secrets.SSH_PORT }}
          remote-path: ${{ secrets.REMOTE_SSH }}:/srv/toltec/stable
      - name: Trigger website rebuild
        run: gh api repos/toltec-dev/web/dispatches -f event_type='update-bootstrap-from-stable'
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      - name: Create Github Release
        continue-on-error: true
        run: |
          sudo apt-get update && sudo apt-get install -y hub
          hub release create -t $SHA -m $MESSAGE $(date +%G-W%V-%u)
        env:
          SHA: ${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          MESSAGE: ${{ github.event.commits[0].message }}
      - name: Send notification to Discord
        continue-on-error: true
        uses: ./.github/actions/discord-send
        with:
          channel: ${{ secrets.DISCORD_STABLE_CHANNEL_ID }}
          token: ${{ secrets.DISCORD_STABLE_CHANNEL_TOKEN }}
          title: New Toltec stable update available
          link: https://toltec-dev.org/stable
          color: 0x2ea043
          message: ${{ github.event.commits[0].message }}
