#!/usr/bin/env bash
# Copyright (c) 2025 The Toltec Contributors
# SPDX-License-Identifier: MIT

archs=(rm1 rm2)
pkgnames=(fuseki)
pkgdesc="Go frontend using GnuGo"
url="https://github.com/palfrey/fuseki"
pkgver=0.1.0-2
timestamp=2025-08-25T16:56+0100
section=games
maintainer="Tom Parker-Shemilt <palfrey@tevps.net>"
license=AGPL-3.0-or-later
image=rust:v3.3
source=(
    "https://github.com/palfrey/fuseki/archive/refs/tags/${pkgver%-*}.zip"
    fuseki-runner.draft
    fuseki-runner
)
sha256sums=(
    df80c15531ac5bcd18e1af684443454ba29dddacc157c24e0db0eb88e37176d0
    SKIP
    SKIP
)

installdepends=("gnugo")

build() {
    cargo build --release
}

package() {
    install -D -m 755 "$srcdir"/target/armv7-unknown-linux-gnueabihf/release/fuseki "$pkgdir"/opt/bin/fuseki
    install -D -m 644 "$srcdir"/fuseki-runner.draft "$pkgdir"/opt/etc/draft/fuseki.draft
    install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/fuseki-runner
    install -D -m 644 "$srcdir"/fuseki.png "$pkgdir"/opt/etc/draft/icons/fuseki.png
}
