#!/usr/bin/env bash
# Copyright (c) 2025 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(fuseki)
pkgdesc="Go frontend using GnuGo"
url="https://github.com/palfrey/fuseki"
pkgver=0.0.1-1
timestamp=2025-08-25T16:56+0100
section=games
maintainer="Tom Parker-Shemilt <palfrey@tevps.net>"
license=AGPL-3.0-or-later
image=rust:v3.1
source=(
    https://github.com/palfrey/fuseki/archive/638191be13be06a8d7428e7739ed947904ef3e56.zip
    fuseki.draft
    fuseki-runner
)
sha256sums=(
    37e4ff419a5a697039e9aa9e5b156248fcf6ed7a97867aae13aa623a7ee6a6ea
    SKIP
    SKIP
)

installdepends=("gnugo")

build() {
    cargo build --release
}

package() {
    install -D -m 755 "$srcdir"/target/armv7-unknown-linux-gnueabihf/release/fuseki "$pkgdir"/opt/bin/fuseki
    install -D -m 644 -t "$pkgdir"/opt/etc/draft "$srcdir"/fuseki.draft
    install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/fuseki-runner
    install -D "$srcdir"/fuseki.png "$pkgdir"/etc/draft/icons/fuseki.png
}
