#!/usr/bin/env bash
# Copyright (c) 2021 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(bufshot dumbskull genie harmony iago lamp mines nao remux rpncalc simple wordlet)
timestamp=2022-03-15T09:18:10Z
maintainer="raisjn <of.raisjn@gmail.com>"
license=MIT
installdepends=(display)
flags=(patch_rm2fb)

image=python:v2.1
source=(
    https://github.com/rmkit-dev/rmkit/archive/f014604ffc129e69938bd84635a2202a21f388b6.zip
    remux.service
    genie.service
)
sha256sums=(
    e710c3864a40cec39d6960726f49f98ab9a849769b9c7e134e6db04f283863fa
    SKIP
    SKIP
)

build() {
    pip3 install okp
    ARCH="rm" make
}

bufshot() {
    pkgdesc="program for saving the framebuffer as a png"
    url="https://github.com/rmkit-dev/rmkit/tree/master/src/bufshot"
    pkgver=0.1.2-2
    section="utils"

    package() {
        install -D -m 755 "$srcdir"/src/build/bufshot "$pkgdir"/opt/bin/bufshot
    }
}

dumbskull() {
    pkgdesc="Dungeon Crawl themed Solitaire"
    url="https://rmkit.dev/apps/dumbskull"
    pkgver=0.0.1-2
    section="games"

    package() {
        install -D -m 755 "$srcdir"/src/build/dumbskull "$pkgdir"/opt/bin/dumbskull
        install -D -m 644 "$srcdir"/src/dumbskull/dumbskull.draft "$pkgdir"/opt/etc/draft/dumbskull.draft
    }

}

genie() {
    pkgdesc="Gesture engine that connects commands to gestures"
    url="https://rmkit.dev/apps/genie"
    pkgver=0.1.6-2
    section="utils"

    package() {
        install -D -m 755 "$srcdir"/src/build/genie "$pkgdir"/opt/bin/genie
        install -D -m 644 "$srcdir"/genie.service "$pkgdir"/lib/systemd/system/genie.service
        install -D -m 644 "$srcdir"/src/genie/example.conf "$pkgdir"/opt/etc/genie.example.conf
    }

    configure() {
        systemctl daemon-reload
        echo "Run 'systemctl enable genie --now' to enable genie"
    }

    preremove() {
        echo "Disabling $pkgname"
        systemctl disable --now "$pkgname"
    }

    postremove() {
        systemctl daemon-reload
    }
}

harmony() {
    pkgdesc="Procedural sketching app"
    url="https://rmkit.dev/apps/harmony"
    pkgver=0.2.0-1
    section="drawing"

    package() {
        install -D -m 755 "$srcdir"/src/build/harmony "$pkgdir"/opt/bin/harmony
        install -D -m 644 "$srcdir"/src/harmony/harmony.draft "$pkgdir"/opt/etc/draft/harmony.draft
        install -D -m 644 "$srcdir"/src/harmony/harmony.png "$pkgdir"/opt/etc/draft/icons/harmony.png
    }

    configure() {
        mkdir -p /home/root/harmony/saved_images
    }
}

iago() {
    pkgdesc="overlay for drawing shapes via stroke injection"
    url="https://rmkit.dev/apps/iago"
    pkgver=0.1.1-2
    section="utils"
    installdepends+=("lamp")

    package() {
        install -D -m 755 "$srcdir"/src/build/iago "$pkgdir"/opt/bin/iago
    }
}

lamp() {
    pkgdesc="config based stroke injection utility"
    url="https://rmkit.dev/apps/lamp"
    pkgver=0.1.1-2
    section="utils"

    package() {
        install -D -m 755 "$srcdir"/src/build/lamp "$pkgdir"/opt/bin/lamp
    }
}

mines() {
    pkgdesc="Mine detection game"
    url="https://rmkit.dev/apps/minesweeper"
    pkgver=0.1.4-2
    section="games"

    package() {
        install -D -m 755 "$srcdir"/src/build/mines "$pkgdir"/opt/bin/mines
        install -D -m 644 "$srcdir"/src/minesweeper/mines.draft "$pkgdir"/opt/etc/draft/mines.draft
        install -D -m 644 "$srcdir"/src/minesweeper/mines1.png "$pkgdir"/opt/etc/draft/icons/mines.png
    }
}

nao() {
    pkgdesc="Nao Package Manager: opkg UI built with SAS"
    url="https://rmkit.dev/apps/nao"
    pkgver=0.1.2-3
    section="admin"
    installdepends+=(simple)

    package() {
        install -D -m 755 "$srcdir"/src/build/nao.sh "$pkgdir"/opt/bin/nao
        install -D -m 644 "$srcdir"/src/nao/nao.draft "$pkgdir"/opt/etc/draft/nao.draft
        install -D -m 644 "$srcdir"/src/nao/nao.png "$pkgdir"/opt/etc/draft/icons/nao.png
    }
}

remux() {
    pkgdesc="Launcher that supports multi-tasking applications"
    url="https://rmkit.dev/apps/remux"
    pkgver=0.2.2-1
    section="launchers"

    package() {
        install -D -m 755 "$srcdir"/src/build/remux "$pkgdir"/opt/bin/remux
        install -D -m 644 "$srcdir"/remux.service "$pkgdir"/lib/systemd/system/remux.service
    }

    configure() {
        systemctl daemon-reload

        if ! is-enabled "$pkgname.service"; then
            echo ""
            echo "Run the following command(s) to use $pkgname as your launcher"
            how-to-enable "$pkgname.service"
            echo ""
        fi
    }

    preremove() {
        echo "Disabling $pkgname"
        systemctl disable --now "$pkgname"
    }

    postremove() {
        systemctl daemon-reload
    }
}

rpncalc() {
    pkgdesc="RPN Calculator"
    url="https://rmkit.dev/apps/rpncalc"
    pkgver=0.0.2-2
    section="math"

    package() {
        install -D -m 755 "$srcdir"/src/build/rpncalc "$pkgdir"/opt/bin/rpncalc
        install -D -m 644 "$srcdir"/src/rpncalc/rpncalc.draft "$pkgdir"/opt/etc/draft/rpncalc.draft
        install -D -m 644 "$srcdir"/src/rpncalc/rpncalc.png "$pkgdir"/opt/etc/draft/icons/rpncalc.png
    }

}

simple() {
    pkgdesc="Simple app script for writing scripted applications"
    url="https://rmkit.dev/apps/sas"
    pkgver=0.1.5-2
    section="devel"

    package() {
        install -D -m 755 "$srcdir"/src/build/simple "$pkgdir"/opt/bin/simple
    }
}

wordlet() {
    pkgdesc="Wordle clone"
    url="https://rmkit.dev/apps/wordlet"
    pkgver=0.0.1-2
    section="games"

    package() {
        install -D -m 755 "$srcdir"/src/build/wordlet "$pkgdir"/opt/bin/wordlet
        install -D -m 644 "$srcdir"/src/wordlet/wordlet.draft "$pkgdir"/opt/etc/draft/wordlet.draft
    }

}
