#!/usr/bin/env bash
# Copyright (c) 2020 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(harmony mines nao remux simple)
timestamp=2020-10-10T01:41+00:00
maintainer="raisjn <of.raisjn@gmail.com>"
license=MIT

image=python:v1.1
source=(
    https://github.com/rmkit-dev/rmkit/archive/9dd3f97e83fa0ec5343c48a9792b40c0c8e23ba4.zip
    remux.service
)
sha256sums=(
    247c8c935442b09a77562f2fd8a04969b9c2f07e6df80d923c6d6103e556581a
    SKIP
)

build() {
    pip3 install okp
    make
}

harmony() {
    pkgdesc="Procedural sketching app"
    url="https://rmkit.dev/apps/harmony"
    pkgver=0.1.0-3
    section=drawing

    package() {
        install -D -m 755 "$srcdir"/src/build/harmony "$pkgdir"/opt/bin/harmony
        install -D -m 644 "$srcdir"/src/harmony/harmony.draft "$pkgdir"/opt/etc/draft/harmony.draft
    }

    configure() {
        mkdir -p /home/root/harmony/saved_images
    }
}

mines() {
    pkgdesc="Mine detection game"
    url="https://rmkit.dev/apps/minesweeper"
    pkgver=0.1.0-2
    section=games

    package() {
        install -D -m 755 "$srcdir"/src/build/mines "$pkgdir"/opt/bin/mines
        install -D -m 644 "$srcdir"/src/minesweeper/mines.draft "$pkgdir"/opt/etc/draft/mines.draft
    }
}

nao() {
    pkgdesc="Nao Package Manager: opkg UI built with SAS"
    url="https://rmkit.dev/apps/nao"
    pkgver=0.1.0-2
    section=utils
    depends=(simple)

    package() {
        install -D -m 755 "$srcdir"/src/build/nao.sh "$pkgdir"/opt/bin/nao
        install -D -m 644 "$srcdir"/src/nao/nao.draft "$pkgdir"/opt/etc/draft/nao.draft
    }
}

remux() {
    pkgdesc="App launcher that supports multi-tasking applications"
    url="https://rmkit.dev/apps/remux"
    pkgver=0.1.2-1
    section=launchers

    package() {
        install -D -m 755 "$srcdir"/src/build/remux "$pkgdir"/opt/bin/remux
        install -D -m 644 "$srcdir"/remux.service "$pkgdir"/lib/systemd/system/remux.service
    }

    configure() {
        systemctl daemon-reload

        if ! is-enabled "$pkgname.service"; then
            echo ""
            echo "Run the following command(s) to use $pkgname as your launcher"
            how-to-enable "$pkgname.service"
            echo ""
        fi
    }

    preremove() {
        echo "Disabling $pkgname"
        systemctl disable --now "$pkgname"
    }

    postremove() {
        systemctl daemon-reload
    }
}

simple() {
    pkgdesc="Simple app script for writing scripted applications"
    url="https://rmkit.dev/apps/sas"
    pkgver=0.1.0-2
    section=utils

    package() {
        install -D -m 755 "$srcdir"/src/build/simple "$pkgdir"/opt/bin/simple
    }
}
