#!/usr/bin/env bash
# Copyright (c) 2020 The Toltec Contributors
# SPDX-License-Identifier: MIT

archs=(rm1 rm2 rmpp rmppm)
pkgnames=(quickjs)
pkgdesc="A small and embeddable Javascript engine"
url=https://bellard.org/quickjs/
pkgver=2025-09-13-2
section="devel"
timestamp=2025-09-13T00:00Z
maintainer="khanhas <xuankhanh963@gmail.com>"
license=MIT

image=base:v3.2
image_rmpp=base:v4.0
image_rmppm=base:v4.0

source=(
    https://bellard.org/quickjs/quickjs-2025-09-13-2.tar.xz
)
sha256sums=(
    996c6b5018fc955ad4d06426d0e9cb713685a00c825aa5c0418bd53f7df8b0b4
)

build() {
    make CROSS_PREFIX="$CROSS_COMPILE" qjs qjsc
}

package() {
    install -d "$pkgdir"/opt/bin
    install -D -m 755 -t "$pkgdir"/opt/bin/ "$srcdir"/qjs
    install -D -m 755 -t "$pkgdir"/opt/bin/ "$srcdir"/qjsc
}
